/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Customer;

import Admin.A_LoginAdmin;
import dao.DAO_Login;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Model_Login;
import service.Service_Login;

/**
 *
 * @author harlan
 */
public class A_LoginCustomer extends javax.swing.JFrame {
    int xx, xy;
    private Service_Login servis = new DAO_Login();
    
    public static boolean tutup = false;

    /**
     * Creates new form Login
     */
    public A_LoginCustomer() {
        initComponents();
        
        LoginButton.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        NameMaskapai = new javax.swing.JLabel();
        Left = new javax.swing.JPanel();
        Copyright = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        Right = new javax.swing.JPanel();
        Login = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        UsernameField = new javax.swing.JTextField();
        WarningUsername = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        WarningPassword = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        Dont = new javax.swing.JLabel();
        ClickHere = new javax.swing.JLabel();
        Admin = new javax.swing.JLabel();
        ClickHere1 = new javax.swing.JLabel();
        AboutLogo = new javax.swing.JLabel();
        AboutText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nine Airlines (Login)");
        setBackground(new java.awt.Color(255, 255, 255));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(0, 153, 255));
        Header.setToolTipText("");
        Header.setPreferredSize(new java.awt.Dimension(900, 150));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NameMaskapai.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NameMaskapai.setForeground(new java.awt.Color(255, 255, 255));
        NameMaskapai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/NameMaskapai.png"))); // NOI18N
        Header.add(NameMaskapai, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Left.setBackground(new java.awt.Color(0, 153, 255));
        Left.setPreferredSize(new java.awt.Dimension(450, 650));
        Left.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Copyright.setText("© 2024 Nine Airlines.");
        Copyright.setPreferredSize(new java.awt.Dimension(130, 20));
        Copyright.setRequestFocusEnabled(false);
        Left.add(Copyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 170, -1));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/LogoMaskapai.png"))); // NOI18N
        Left.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 30, -1, -1));

        getContentPane().add(Left, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        Right.setBackground(new java.awt.Color(255, 255, 255));
        Right.setPreferredSize(new java.awt.Dimension(450, 650));
        Right.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        Login.setText("LOGIN");
        Right.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 100, -1, -1));

        Username.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Username.setForeground(new java.awt.Color(102, 102, 102));
        Username.setText("Username :");
        Right.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 100, 20));

        UsernameField.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Right.add(UsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 300, 35));

        WarningUsername.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        WarningUsername.setForeground(new java.awt.Color(255, 0, 0));
        Right.add(WarningUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 300, 25));

        Password.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Password.setForeground(new java.awt.Color(102, 102, 102));
        Password.setText("Password :");
        Right.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 100, 20));

        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });
        Right.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 300, 35));

        WarningPassword.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        WarningPassword.setForeground(new java.awt.Color(255, 0, 0));
        Right.add(WarningPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 300, 25));

        LoginButton.setText("LOGIN");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        Right.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, -1, -1));

        Dont.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Dont.setText("Don't have an account ?");
        Right.add(Dont, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, -1, -1));

        ClickHere.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        ClickHere.setText("Click here !");
        ClickHere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClickHereMouseClicked(evt);
            }
        });
        Right.add(ClickHere, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, -1, -1));

        Admin.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Admin.setText("Login as Admin ?");
        Right.add(Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, -1, -1));

        ClickHere1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        ClickHere1.setText("Click here !");
        ClickHere1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClickHere1MouseClicked(evt);
            }
        });
        Right.add(ClickHere1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 580, -1, -1));

        AboutLogo.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        AboutLogo.setForeground(new java.awt.Color(255, 255, 255));
        AboutLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/About.png"))); // NOI18N
        AboutLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutLogoMouseClicked(evt);
            }
        });
        Right.add(AboutLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 590, 30, 70));

        AboutText.setBackground(new java.awt.Color(204, 204, 204));
        AboutText.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        AboutText.setForeground(new java.awt.Color(102, 102, 102));
        AboutText.setText(" About");
        AboutText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutTextMouseClicked(evt);
            }
        });
        Right.add(AboutText, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 590, 60, 70));

        getContentPane().add(Right, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
        prosesLogin();
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void ClickHereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClickHereMouseClicked
        // TODO add your handling code here:
        A_SignUp SignUp = new A_SignUp();
        SignUp.setVisible(true);
        SignUp.revalidate();
            
        dispose();
    }//GEN-LAST:event_ClickHereMouseClicked

    private void ClickHere1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClickHere1MouseClicked
        // TODO add your handling code here:
        A_LoginAdmin LoginAdmin = new A_LoginAdmin();
        LoginAdmin.setVisible(true);
        LoginAdmin.revalidate();
            
        dispose();
    }//GEN-LAST:event_ClickHere1MouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void AboutLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutLogoMouseClicked
        new Z_About().setVisible(true);
    }//GEN-LAST:event_AboutLogoMouseClicked

    private void AboutTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutTextMouseClicked
        new Z_About().setVisible(true);
    }//GEN-LAST:event_AboutTextMouseClicked

    /**
     * @param args the command line arguments
     */
//    public void A_LoginCustomer(){
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(A_LoginCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(A_LoginCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(A_LoginCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(A_LoginCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new A_LoginCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AboutLogo;
    private javax.swing.JLabel AboutText;
    private javax.swing.JLabel Admin;
    private javax.swing.JLabel ClickHere;
    private javax.swing.JLabel ClickHere1;
    private javax.swing.JLabel Copyright;
    private javax.swing.JLabel Dont;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Left;
    private javax.swing.JLabel Login;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel NameMaskapai;
    private javax.swing.JLabel Password;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JPanel Right;
    private javax.swing.JLabel Username;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JLabel WarningPassword;
    private javax.swing.JLabel WarningUsername;
    // End of variables declaration//GEN-END:variables

    private void prosesLogin(){
        if(validasiInput()== true){
            String username = UsernameField.getText();
            String password = PasswordField.getText();

            model.Model_Login mod_log = new Model_Login();

            mod_log.setUsername(username);
            mod_log.setPassword(password);

            servis.prosesLogin(mod_log);
            if(tutup){
                dispose();
            }
        }
    }
    
    private boolean validasiInput(){
        boolean valid = false;
            if("".equals(UsernameField.getText().trim())){
                JOptionPane.showMessageDialog(new JFrame(),"Username is required","Error",JOptionPane.ERROR_MESSAGE);
            }else if("".equals(PasswordField.getText().trim())){
                JOptionPane.showMessageDialog(new JFrame(),"Password is required","Error",JOptionPane.ERROR_MESSAGE);
            }else{
                valid = true;
            }
            return valid;      
    }
    
}