/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Customer;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author harlan
 */
public class A_SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public A_SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        NameMaskapai = new javax.swing.JLabel();
        Left = new javax.swing.JPanel();
        Copyright = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        Right = new javax.swing.JPanel();
        SignUp = new javax.swing.JLabel();
        FullName = new javax.swing.JLabel();
        FullNameField = new javax.swing.JTextField();
        Username = new javax.swing.JLabel();
        UsernameField = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        SignUpButton = new javax.swing.JButton();
        Already = new javax.swing.JLabel();
        ClickHere = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nine Airlines (Sign Up)");

        Header.setBackground(new java.awt.Color(0, 153, 255));
        Header.setToolTipText("");
        Header.setPreferredSize(new java.awt.Dimension(900, 150));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NameMaskapai.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NameMaskapai.setForeground(new java.awt.Color(255, 255, 255));
        NameMaskapai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/NameMaskapai.png"))); // NOI18N
        Header.add(NameMaskapai, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        Left.setBackground(new java.awt.Color(0, 153, 255));
        Left.setPreferredSize(new java.awt.Dimension(450, 650));
        Left.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Copyright.setText("© 2024 Nine Airlines.");
        Copyright.setPreferredSize(new java.awt.Dimension(130, 20));
        Copyright.setRequestFocusEnabled(false);
        Left.add(Copyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, -1, -1));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/LogoMaskapai.png"))); // NOI18N
        Left.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 30, -1, -1));

        Right.setBackground(new java.awt.Color(255, 255, 255));
        Right.setPreferredSize(new java.awt.Dimension(450, 650));
        Right.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SignUp.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        SignUp.setText("SIGN UP");
        Right.add(SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        FullName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FullName.setForeground(new java.awt.Color(102, 102, 102));
        FullName.setText("Full Name:");
        Right.add(FullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 100, 20));

        FullNameField.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Right.add(FullNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 300, 35));

        Username.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Username.setForeground(new java.awt.Color(102, 102, 102));
        Username.setText("Username :");
        Right.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 100, 20));

        UsernameField.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Right.add(UsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 300, 35));

        Password.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Password.setForeground(new java.awt.Color(102, 102, 102));
        Password.setText("Password :");
        Right.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 100, 20));

        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });
        Right.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 300, 35));

        SignUpButton.setText("Sign Up");
        SignUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpButtonActionPerformed(evt);
            }
        });
        Right.add(SignUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, -1, -1));

        Already.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Already.setText("Already have an account ?");
        Right.add(Already, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, -1, -1));

        ClickHere.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        ClickHere.setText("Click here !");
        ClickHere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClickHereMouseClicked(evt);
            }
        });
        Right.add(ClickHere, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Left, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(Right, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Left, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Right, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void SignUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpButtonActionPerformed
        // TODO add your handling code here:
        String F_name,username,password;
         
        F_name = FullNameField.getText();
        username = UsernameField.getText();
        password = PasswordField.getText();
         
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/nineairlines", "root", "");
            Statement stat = con.createStatement();    
            String selectQuery = "select * from customer where F_name='"+F_name+"'and username='"+username+"' and password='"+password+"'";
            System.out.println(selectQuery);
            ResultSet rs=stat.executeQuery(selectQuery);
            boolean accountExists = rs.next();
           
           if(accountExists){
             JOptionPane.showConfirmDialog(null,"Account found, please Login ","Ticket Booking", JOptionPane.WARNING_MESSAGE);
           }
           else{
                if("".equals(UsernameField.getText())){
                    JOptionPane.showMessageDialog(new JFrame(),"Username is required","Error",JOptionPane.ERROR_MESSAGE);
                }else if("".equals(PasswordField.getText())){
                    JOptionPane.showMessageDialog(new JFrame(),"Password is required","Error",JOptionPane.ERROR_MESSAGE);
                }else{
                    F_name = FullNameField.getText();
                    username = UsernameField.getText();
                    password = PasswordField.getText();
                    
                    String insertQuery = "insert into customer (F_name, username, password) values('" + F_name + "','" + username + "','" + password + "');";

                    stat.executeUpdate(insertQuery);
                
                FullNameField.setText(null);
                UsernameField.setText(null);
                PasswordField.setText(null);
                JOptionPane.showConfirmDialog(null,"Account Created!","Ticket Booking", JOptionPane.WARNING_MESSAGE);
                
                A_LoginCustomer LoginCustomer = new A_LoginCustomer();
                LoginCustomer.setVisible(true);
                LoginCustomer.revalidate();
            
                dispose();
            }
           }
        }
        catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_SignUpButtonActionPerformed

    private void ClickHereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClickHereMouseClicked
        // TODO add your handling code here:
        A_LoginCustomer LoginCustomer = new A_LoginCustomer();
        LoginCustomer.setVisible(true);
        LoginCustomer.revalidate();
            
        dispose();
    }//GEN-LAST:event_ClickHereMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(A_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(A_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(A_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(A_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new A_SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Already;
    private javax.swing.JLabel ClickHere;
    private javax.swing.JLabel Copyright;
    private javax.swing.JLabel FullName;
    private javax.swing.JTextField FullNameField;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Left;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel NameMaskapai;
    private javax.swing.JLabel Password;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JPanel Right;
    private javax.swing.JLabel SignUp;
    private javax.swing.JButton SignUpButton;
    private javax.swing.JLabel Username;
    private javax.swing.JTextField UsernameField;
    // End of variables declaration//GEN-END:variables

}