/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Customer;

import java.awt.Image;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Model_Login;
import com.toedter.calendar.JDateChooser;

/**
 *
 * @author harlan
 */
public class B_Destination extends javax.swing.JFrame {
    private Model_Login modelLogin;

    /**
     * Creates new form B_Destination
     */
    public B_Destination(Model_Login modelLogin) {
        this.modelLogin = modelLogin;
        initComponents();
        
        if (modelLogin != null) {
            NamaLengkap.setText(modelLogin.getNama());

            try{
                if (modelLogin.getGambar() != null) {
                //Konversi blob gambar ke ImageIcon
                byte[] img = modelLogin.getGambar().getBytes(1,(int)modelLogin.getGambar().length());
                ImageIcon imageIcon = new ImageIcon(img);

                //ukuran JLabel
                int labelWidth = 100;
                int labelHeight = 300;

                //ukuran gambar asli
                int imageWidth = imageIcon.getIconWidth();
                int imageHeight = imageIcon.getIconHeight();

                //hitung skala untuk ukuran gambar yang baru
                double scaleX =(double) labelWidth / (double) imageWidth;
                double scaleY = (double) labelHeight / (double) imageHeight;
                double scale = Math.min(scaleX, scaleY);

                //ubah ukuran gambar dengan skala yang sudah dihitung
                Image scaledImage = imageIcon.getImage().getScaledInstance((int) (scale * imageWidth), (int)(scale*imageHeight), Image.SCALE_SMOOTH);

                //tampilkan ImageIcon pada JLabel
                Photos.setIcon(new ImageIcon(scaledImage));
                }else{
                    Photos.setText("No Image");
                }
            }catch (SQLException ex){
                Logger.getLogger(B_Destination.class.getName()).log(Level.SEVERE, null,ex);
            }
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        Profile = new javax.swing.JPanel();
        Photo = new javax.swing.JPanel();
        Photos = new javax.swing.JLabel();
        Hi = new javax.swing.JLabel();
        NamaLengkap = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        NameMaskapai1 = new javax.swing.JLabel();
        CircleEnable1 = new javax.swing.JLabel();
        CircleDisable2 = new javax.swing.JLabel();
        CircleDisable3 = new javax.swing.JLabel();
        CircleDisable4 = new javax.swing.JLabel();
        CircleDisable5 = new javax.swing.JLabel();
        Line = new javax.swing.JLabel();
        Progress1 = new javax.swing.JLabel();
        Progress2 = new javax.swing.JLabel();
        Progress3 = new javax.swing.JLabel();
        Progress4 = new javax.swing.JLabel();
        Progress5 = new javax.swing.JLabel();
        Bottom = new javax.swing.JPanel();
        Depart = new javax.swing.JLabel();
        Please = new javax.swing.JLabel();
        DepartureLabel = new javax.swing.JLabel();
        Departure = new javax.swing.JComboBox<>();
        DestinationLabel = new javax.swing.JLabel();
        Destination = new javax.swing.JComboBox<>();
        DateLabel = new javax.swing.JLabel();
        NextButton = new javax.swing.JButton();
        Copyright = new javax.swing.JLabel();
        date = new JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nine Airlines (Destination)");

        Header.setBackground(new java.awt.Color(0, 153, 255));
        Header.setToolTipText("");
        Header.setPreferredSize(new java.awt.Dimension(900, 150));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Profile.setBackground(new java.awt.Color(0, 153, 255));

        Photo.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PhotoLayout = new javax.swing.GroupLayout(Photo);
        Photo.setLayout(PhotoLayout);
        PhotoLayout.setHorizontalGroup(
            PhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Photos, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        PhotoLayout.setVerticalGroup(
            PhotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PhotoLayout.createSequentialGroup()
                .addComponent(Photos, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addContainerGap())
        );

        Hi.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Hi.setForeground(new java.awt.Color(255, 255, 255));
        Hi.setText("Hi,");

        NamaLengkap.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        NamaLengkap.setForeground(new java.awt.Color(255, 255, 255));
        NamaLengkap.setText("Nama Lengkap");

        Logout.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        Edit.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Edit.setText("Edit Profile");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProfileLayout = new javax.swing.GroupLayout(Profile);
        Profile.setLayout(ProfileLayout);
        ProfileLayout.setHorizontalGroup(
            ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileLayout.createSequentialGroup()
                .addComponent(Photo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfileLayout.createSequentialGroup()
                        .addComponent(Hi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NamaLengkap, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Logout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Edit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 24, Short.MAX_VALUE))
        );
        ProfileLayout.setVerticalGroup(
            ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ProfileLayout.createSequentialGroup()
                        .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Hi)
                            .addComponent(NamaLengkap))
                        .addGap(18, 18, 18)
                        .addComponent(Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Logout)
                        .addGap(11, 11, 11))
                    .addComponent(Photo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Header.add(Profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 110));

        NameMaskapai1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NameMaskapai1.setForeground(new java.awt.Color(255, 255, 255));
        NameMaskapai1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/NameMaskapai.png"))); // NOI18N
        Header.add(NameMaskapai1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, -1, -1));

        CircleEnable1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Circle.png"))); // NOI18N
        Header.add(CircleEnable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, -1, -1));

        CircleDisable2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CircleDisable.png"))); // NOI18N
        Header.add(CircleDisable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, -1, -1));

        CircleDisable3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CircleDisable.png"))); // NOI18N
        Header.add(CircleDisable3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, -1, -1));

        CircleDisable4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CircleDisable.png"))); // NOI18N
        Header.add(CircleDisable4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, -1, -1));

        CircleDisable5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CircleDisable.png"))); // NOI18N
        Header.add(CircleDisable5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 110, -1, -1));

        Line.setForeground(new java.awt.Color(21, 30, 158));
        Line.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Line.png"))); // NOI18N
        Header.add(Line, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 105, 300, 30));

        Progress1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Progress1.setForeground(new java.awt.Color(255, 255, 255));
        Progress1.setText("Destination");
        Header.add(Progress1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, -1, -1));

        Progress2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Progress2.setForeground(new java.awt.Color(21, 30, 158));
        Progress2.setText("Seats");
        Header.add(Progress2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, -1, -1));

        Progress3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Progress3.setForeground(new java.awt.Color(21, 30, 158));
        Progress3.setText("Passenger");
        Header.add(Progress3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, -1, -1));

        Progress4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Progress4.setForeground(new java.awt.Color(21, 30, 158));
        Progress4.setText("Bill");
        Header.add(Progress4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 130, -1, -1));

        Progress5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Progress5.setForeground(new java.awt.Color(21, 30, 158));
        Progress5.setText("Confirm");
        Header.add(Progress5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 90, -1, -1));

        Bottom.setBackground(new java.awt.Color(255, 255, 255));
        Bottom.setPreferredSize(new java.awt.Dimension(900, 650));
        Bottom.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Depart.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        Depart.setText("Depart");
        Bottom.add(Depart, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        Please.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Please.setForeground(new java.awt.Color(102, 102, 102));
        Please.setText("Please fill in the following flight data :");
        Bottom.add(Please, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 300, 20));

        DepartureLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        DepartureLabel.setForeground(new java.awt.Color(102, 102, 102));
        DepartureLabel.setText("Deperature :");
        Bottom.add(DepartureLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 100, 20));

        Departure.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Jakarta (CGK)", "Singapore (SIN)", "Kuala Lumpur (KUL)" }));
        Departure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartureActionPerformed(evt);
            }
        });
        Bottom.add(Departure, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 240, 40));

        DestinationLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        DestinationLabel.setForeground(new java.awt.Color(102, 102, 102));
        DestinationLabel.setText("Destination :");
        Bottom.add(DestinationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 100, 20));

        Destination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Jakarta (CGK)", "Singapore (SIN)", "Kuala Lumpur (KUL)" }));
        Bottom.add(Destination, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 240, 40));

        DateLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        DateLabel.setForeground(new java.awt.Color(102, 102, 102));
        DateLabel.setText("Departure Date :");
        Bottom.add(DateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 240, 20));

        NextButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NextButton.setText("NEXT");
        NextButton.setFocusPainted(false);
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });
        Bottom.add(NextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 498, 100, 40));

        Copyright.setText("© 2024 Nine Airlines.");
        Copyright.setPreferredSize(new java.awt.Dimension(130, 20));
        Copyright.setRequestFocusEnabled(false);
        Bottom.add(Copyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 611, 141, -1));
        Bottom.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 240, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Bottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Bottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_DatePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_DatePropertyChange

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
        // TODO add your handling code here:
        if((Departure.getSelectedIndex()) == (Destination.getSelectedIndex())){
            if((Departure.getSelectedIndex()>0) && Destination.getSelectedIndex()>0){
                JOptionPane.showConfirmDialog(null,"Same place can't be choosed","Ticket Booking",
                    JOptionPane.WARNING_MESSAGE);
            }else if (Departure.getSelectedIndex()==0){
                JOptionPane.showConfirmDialog(null,"From Data is required","Ticket Booking",
                    JOptionPane.WARNING_MESSAGE);
            }else if (Destination.getSelectedIndex()==0){
                JOptionPane.showConfirmDialog(null,"To Data is required","Ticket Booking",
                    JOptionPane.WARNING_MESSAGE);
            }
        }else if(date.getDate() == null){
            JOptionPane.showConfirmDialog(null,"Please insert Date","Ticket Booking",
                JOptionPane.WARNING_MESSAGE);
        }else {
            int selectedIndex = Departure.getSelectedIndex();
        String text = "";
        String text1 = "";
        switch (selectedIndex) {
            case 1:
                text = "CGK";
                text1 = "Jakarta";
                break;
            case 2:
                text = "SIN";
                text1="Singapore";
                break;
            case 3:
                text = "KUL";
                text1 = "Kuala Lumpur";
                break;
        }
        int selectedIndeks = Destination.getSelectedIndex();
        String teks = "";
        String teks1 = "";
        switch (selectedIndeks) {
            case 1:
                teks = "CGK";
                teks1 = "Jakarta";
                break;
            case 2:
                teks = "SIN";
                teks1 = "Singapore";
                break;
            case 3:
                teks = "KUL";
                teks1 = "Kuala Lumpur";
                break;
        }
        
            date.setDateFormatString("dd-MM-yyyy");
            Date selectedDate = date.getDate();

            C_Book C_Book = new C_Book(selectedDate, text, teks, modelLogin);
            C_Book.setDate(selectedDate);
            C_Book.setLabelText(text);
            C_Book.setLabelText1(text1);
            C_Book.setLabelTeks(teks);
            C_Book.setLabelTeks1(teks1);
            C_Book.setVisible(true);
            C_Book.revalidate();
            dispose();
            
        }
    }//GEN-LAST:event_NextButtonActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        A_LoginCustomer A_LoginCustomer = new A_LoginCustomer();
        A_LoginCustomer.setVisible(true);
        A_LoginCustomer.revalidate();

        dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    private void DepartureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepartureActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        // TODO add your handling code here:
        profile profilee = new profile(modelLogin);
        profilee.setVisible(true);
        profilee.revalidate();
        
        dispose();
    }//GEN-LAST:event_EditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(B_Destination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(B_Destination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(B_Destination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(B_Destination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Model_Login modelLogin = new Model_Login();
                new B_Destination(modelLogin).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bottom;
    private javax.swing.JLabel CircleDisable2;
    private javax.swing.JLabel CircleDisable3;
    private javax.swing.JLabel CircleDisable4;
    private javax.swing.JLabel CircleDisable5;
    private javax.swing.JLabel CircleEnable1;
    private javax.swing.JLabel Copyright;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JLabel Depart;
    private javax.swing.JComboBox<String> Departure;
    private javax.swing.JLabel DepartureLabel;
    private javax.swing.JComboBox<String> Destination;
    private javax.swing.JLabel DestinationLabel;
    private javax.swing.JButton Edit;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel Hi;
    private javax.swing.JLabel Line;
    private javax.swing.JButton Logout;
    private javax.swing.JLabel NamaLengkap;
    private javax.swing.JLabel NameMaskapai1;
    private javax.swing.JButton NextButton;
    private javax.swing.JPanel Photo;
    private javax.swing.JLabel Photos;
    private javax.swing.JLabel Please;
    private javax.swing.JPanel Profile;
    private javax.swing.JLabel Progress1;
    private javax.swing.JLabel Progress2;
    private javax.swing.JLabel Progress3;
    private javax.swing.JLabel Progress4;
    private javax.swing.JLabel Progress5;
    private JDateChooser date;
    // End of variables declaration//GEN-END:variables

}