/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Customer;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JButton;
import dao.DAO_Seat;
import model.Model_Login;
import service.Service_Seat;
import model.Model_Seat;
/**
 *
 * @author harlan
 */
public class C_Book extends javax.swing.JFrame {
    int xx,xy;
    private Date selectedDate;
    private String text;
    private String text1;
    private String teks;
    private String teks1;
    public static Flight flight = new Flight();
    private Service_Seat servis = new DAO_Seat();
    private Model_Login modelLogin;

    /**
     * Creates new form C_Seats
     */
    public C_Book() {
        initComponents();
        summaryText();
        seatMapShowAvailable();
    }
    
    public C_Book(Date selectedDate,String from, String to, Model_Login modelLogin) {
        this.modelLogin = modelLogin;
        this.text = from;
        this.teks = to;
        this.selectedDate = selectedDate;
        initComponents();
        summaryText();
        seatMapShowAvailable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        NameMaskapai = new javax.swing.JLabel();
        CircleEnable = new javax.swing.JLabel();
        CircleDisable1 = new javax.swing.JLabel();
        CircleDisable2 = new javax.swing.JLabel();
        CircleDisable3 = new javax.swing.JLabel();
        CircleDisable4 = new javax.swing.JLabel();
        Line = new javax.swing.JLabel();
        Progress1 = new javax.swing.JLabel();
        Progress2 = new javax.swing.JLabel();
        Progress3 = new javax.swing.JLabel();
        Progress4 = new javax.swing.JLabel();
        Progress5 = new javax.swing.JLabel();
        Bottom = new javax.swing.JPanel();
        Depart = new javax.swing.JLabel();
        PlaneIcon = new javax.swing.JLabel();
        From = new javax.swing.JLabel();
        DepartureCode = new javax.swing.JLabel();
        DepartureName = new javax.swing.JLabel();
        To = new javax.swing.JLabel();
        DestinationCode = new javax.swing.JLabel();
        DestinationName = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        DateLabel = new javax.swing.JLabel();
        HorizontalSeperator1 = new javax.swing.JSeparator();
        Summary = new javax.swing.JLabel();
        Available = new javax.swing.JLabel();
        AvailableTextShow = new javax.swing.JLabel();
        Booked = new javax.swing.JLabel();
        BookedTextShow = new javax.swing.JLabel();
        Copyright = new javax.swing.JLabel();
        VerticalSeperator1 = new javax.swing.JSeparator();
        SelectSeat = new javax.swing.JLabel();
        LeftDoor = new javax.swing.JPanel();
        LeftExit = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        Toilet = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        Row1 = new javax.swing.JLabel();
        A1 = new javax.swing.JButton();
        B1 = new javax.swing.JButton();
        C1 = new javax.swing.JButton();
        D1 = new javax.swing.JButton();
        E1 = new javax.swing.JButton();
        F1 = new javax.swing.JButton();
        Row2 = new javax.swing.JLabel();
        A2 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        C2 = new javax.swing.JButton();
        D2 = new javax.swing.JButton();
        E2 = new javax.swing.JButton();
        F2 = new javax.swing.JButton();
        Row3 = new javax.swing.JLabel();
        A3 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        C3 = new javax.swing.JButton();
        D3 = new javax.swing.JButton();
        E3 = new javax.swing.JButton();
        F3 = new javax.swing.JButton();
        Row4 = new javax.swing.JLabel();
        A4 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        C4 = new javax.swing.JButton();
        D4 = new javax.swing.JButton();
        E4 = new javax.swing.JButton();
        F4 = new javax.swing.JButton();
        Row5 = new javax.swing.JLabel();
        A5 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        C5 = new javax.swing.JButton();
        D5 = new javax.swing.JButton();
        E5 = new javax.swing.JButton();
        F5 = new javax.swing.JButton();
        Row6 = new javax.swing.JLabel();
        A6 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        C6 = new javax.swing.JButton();
        D6 = new javax.swing.JButton();
        E6 = new javax.swing.JButton();
        F6 = new javax.swing.JButton();
        Row7 = new javax.swing.JLabel();
        A7 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        C7 = new javax.swing.JButton();
        D7 = new javax.swing.JButton();
        E7 = new javax.swing.JButton();
        F7 = new javax.swing.JButton();
        RightDoor = new javax.swing.JPanel();
        RightExit = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        Toilet1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        OwnerName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nine Airlines (Seats)");
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        Header.setBackground(new java.awt.Color(0, 153, 255));
        Header.setToolTipText("");
        Header.setPreferredSize(new java.awt.Dimension(900, 150));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NameMaskapai.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NameMaskapai.setForeground(new java.awt.Color(255, 255, 255));
        NameMaskapai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/NameMaskapai.png"))); // NOI18N
        Header.add(NameMaskapai, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        CircleEnable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CircleDisable.png"))); // NOI18N
        Header.add(CircleEnable, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, -1, -1));

        CircleDisable1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Circle.png"))); // NOI18N
        Header.add(CircleDisable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, -1, -1));

        CircleDisable2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CircleDisable.png"))); // NOI18N
        Header.add(CircleDisable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, -1, -1));

        CircleDisable3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CircleDisable.png"))); // NOI18N
        Header.add(CircleDisable3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, -1, -1));

        CircleDisable4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CircleDisable.png"))); // NOI18N
        Header.add(CircleDisable4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 70, -1, -1));

        Line.setForeground(new java.awt.Color(21, 30, 158));
        Line.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Line.png"))); // NOI18N
        Header.add(Line, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 65, 300, 30));

        Progress1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Progress1.setForeground(new java.awt.Color(21, 30, 158));
        Progress1.setText("Destination");
        Header.add(Progress1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, -1, -1));

        Progress2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Progress2.setForeground(new java.awt.Color(255, 255, 255));
        Progress2.setText("Seats");
        Header.add(Progress2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, -1, -1));

        Progress3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Progress3.setForeground(new java.awt.Color(21, 30, 158));
        Progress3.setText("Passenger");
        Header.add(Progress3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, -1, -1));

        Progress4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Progress4.setForeground(new java.awt.Color(21, 30, 158));
        Progress4.setText("Bill");
        Header.add(Progress4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, -1, -1));

        Progress5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Progress5.setForeground(new java.awt.Color(21, 30, 158));
        Progress5.setText("Confirm");
        Header.add(Progress5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 50, -1, -1));

        Bottom.setBackground(new java.awt.Color(255, 255, 255));
        Bottom.setPreferredSize(new java.awt.Dimension(450, 650));
        Bottom.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Depart.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        Depart.setText("Depart");
        Bottom.add(Depart, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 140, 50));

        PlaneIcon.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        PlaneIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BlackPlane.png"))); // NOI18N
        Bottom.add(PlaneIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 40, -1));

        From.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        From.setForeground(new java.awt.Color(102, 102, 102));
        From.setText("FROM");
        Bottom.add(From, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, 12));

        DepartureCode.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        DepartureCode.setForeground(new java.awt.Color(0, 153, 255));
        DepartureCode.setText("---");
        Bottom.add(DepartureCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, 35));

        DepartureName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        DepartureName.setForeground(new java.awt.Color(102, 102, 102));
        DepartureName.setText("-----");
        Bottom.add(DepartureName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 80, 20));

        To.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        To.setForeground(new java.awt.Color(102, 102, 102));
        To.setText("TO");
        Bottom.add(To, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, 12));

        DestinationCode.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        DestinationCode.setForeground(new java.awt.Color(0, 153, 255));
        DestinationCode.setText("---");
        Bottom.add(DestinationCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, 35));

        DestinationName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        DestinationName.setForeground(new java.awt.Color(102, 102, 102));
        DestinationName.setText("-----");
        Bottom.add(DestinationName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 90, 20));

        Date.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Date.setForeground(new java.awt.Color(102, 102, 102));
        Date.setText("DATE");
        Bottom.add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 80, 12));

        DateLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        DateLabel.setForeground(new java.awt.Color(0, 153, 255));
        DateLabel.setText("---");
        Bottom.add(DateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, 35));
        Bottom.add(HorizontalSeperator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 250, 10));

        Summary.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        Summary.setText("Summary");
        Bottom.add(Summary, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 180, 60));

        Available.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Available.setForeground(new java.awt.Color(102, 102, 102));
        Available.setText("AVAILABLE");
        Bottom.add(Available, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 90, 30));

        AvailableTextShow.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        AvailableTextShow.setText("--");
        Bottom.add(AvailableTextShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 50, -1));

        Booked.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Booked.setForeground(new java.awt.Color(102, 102, 102));
        Booked.setText("BOOKED");
        Bottom.add(Booked, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 80, 30));

        BookedTextShow.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        BookedTextShow.setText("--");
        Bottom.add(BookedTextShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, 50, -1));

        Copyright.setBackground(new java.awt.Color(204, 204, 204));
        Copyright.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Copyright.setForeground(new java.awt.Color(102, 102, 102));
        Copyright.setText("© 2024 Nine Airlines.");
        Bottom.add(Copyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 140, 40));

        VerticalSeperator1.setBackground(new java.awt.Color(0, 0, 0));
        VerticalSeperator1.setForeground(new java.awt.Color(0, 0, 0));
        VerticalSeperator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Bottom.add(VerticalSeperator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 10, 590));

        SelectSeat.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        SelectSeat.setText("Select Seat");
        Bottom.add(SelectSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 200, 50));

        javax.swing.GroupLayout LeftDoorLayout = new javax.swing.GroupLayout(LeftDoor);
        LeftDoor.setLayout(LeftDoorLayout);
        LeftDoorLayout.setHorizontalGroup(
            LeftDoorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        LeftDoorLayout.setVerticalGroup(
            LeftDoorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        Bottom.add(LeftDoor, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 180, 10));

        LeftExit.setBackground(new java.awt.Color(52, 79, 88));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Exit.png"))); // NOI18N

        javax.swing.GroupLayout LeftExitLayout = new javax.swing.GroupLayout(LeftExit);
        LeftExit.setLayout(LeftExitLayout);
        LeftExitLayout.setHorizontalGroup(
            LeftExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftExitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        LeftExitLayout.setVerticalGroup(
            LeftExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftExitLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        Bottom.add(LeftExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 30, 60));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Toilet.png"))); // NOI18N

        javax.swing.GroupLayout ToiletLayout = new javax.swing.GroupLayout(Toilet);
        Toilet.setLayout(ToiletLayout);
        ToiletLayout.setHorizontalGroup(
            ToiletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ToiletLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        ToiletLayout.setVerticalGroup(
            ToiletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToiletLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        Bottom.add(Toilet, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 570, 180, 50));

        Row1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Row1.setForeground(new java.awt.Color(204, 204, 204));
        Row1.setText("1");
        Bottom.add(Row1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 30, 40));

        A1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        A1.setText("A");
        A1.setFocusPainted(false);
        A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1ActionPerformed(evt);
            }
        });
        Bottom.add(A1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 60, 60));

        B1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        B1.setText("B");
        B1.setFocusPainted(false);
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });
        Bottom.add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 60, 60));

        C1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        C1.setText("C");
        C1.setFocusPainted(false);
        C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C1ActionPerformed(evt);
            }
        });
        Bottom.add(C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 60, 60));

        D1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        D1.setText("D");
        D1.setFocusPainted(false);
        D1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D1ActionPerformed(evt);
            }
        });
        Bottom.add(D1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 60, 60));

        E1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        E1.setText("E");
        E1.setFocusPainted(false);
        E1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1ActionPerformed(evt);
            }
        });
        Bottom.add(E1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, 60, 60));

        F1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        F1.setText("F");
        F1.setFocusPainted(false);
        F1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F1ActionPerformed(evt);
            }
        });
        Bottom.add(F1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 120, 60, 60));

        Row2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Row2.setForeground(new java.awt.Color(204, 204, 204));
        Row2.setText("2");
        Bottom.add(Row2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 30, 40));

        A2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        A2.setText("A");
        A2.setFocusPainted(false);
        A2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A2ActionPerformed(evt);
            }
        });
        Bottom.add(A2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 60, 60));

        B2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        B2.setText("B");
        B2.setFocusPainted(false);
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });
        Bottom.add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 60, 60));

        C2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        C2.setText("C");
        C2.setFocusPainted(false);
        C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C2ActionPerformed(evt);
            }
        });
        Bottom.add(C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 60, 60));

        D2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        D2.setText("D");
        D2.setFocusPainted(false);
        D2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D2ActionPerformed(evt);
            }
        });
        Bottom.add(D2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 60, 60));

        E2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        E2.setText("E");
        E2.setFocusPainted(false);
        E2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E2ActionPerformed(evt);
            }
        });
        Bottom.add(E2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, 60, 60));

        F2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        F2.setText("F");
        F2.setFocusPainted(false);
        F2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F2ActionPerformed(evt);
            }
        });
        Bottom.add(F2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 180, 60, 60));

        Row3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Row3.setForeground(new java.awt.Color(204, 204, 204));
        Row3.setText("3");
        Bottom.add(Row3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 30, 40));

        A3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        A3.setText("A");
        A3.setFocusPainted(false);
        A3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A3ActionPerformed(evt);
            }
        });
        Bottom.add(A3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 60, 60));

        B3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        B3.setText("B");
        B3.setFocusPainted(false);
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });
        Bottom.add(B3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 60, 60));

        C3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        C3.setText("C");
        C3.setFocusPainted(false);
        C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C3ActionPerformed(evt);
            }
        });
        Bottom.add(C3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 60, 60));

        D3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        D3.setText("D");
        D3.setFocusPainted(false);
        D3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D3ActionPerformed(evt);
            }
        });
        Bottom.add(D3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, 60, 60));

        E3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        E3.setText("E");
        E3.setFocusPainted(false);
        E3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E3ActionPerformed(evt);
            }
        });
        Bottom.add(E3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 240, 60, 60));

        F3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        F3.setText("F");
        F3.setFocusPainted(false);
        F3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F3ActionPerformed(evt);
            }
        });
        Bottom.add(F3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 240, 60, 60));

        Row4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Row4.setForeground(new java.awt.Color(204, 204, 204));
        Row4.setText("4");
        Bottom.add(Row4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, 30, 40));

        A4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        A4.setText("A");
        A4.setFocusPainted(false);
        A4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A4ActionPerformed(evt);
            }
        });
        Bottom.add(A4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 60, 60));

        B4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        B4.setText("B");
        B4.setFocusPainted(false);
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });
        Bottom.add(B4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 60, 60));

        C4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        C4.setText("C");
        C4.setFocusPainted(false);
        C4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C4ActionPerformed(evt);
            }
        });
        Bottom.add(C4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 60, 60));

        D4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        D4.setText("D");
        D4.setFocusPainted(false);
        D4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D4ActionPerformed(evt);
            }
        });
        Bottom.add(D4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, 60, 60));

        E4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        E4.setText("E");
        E4.setFocusPainted(false);
        E4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E4ActionPerformed(evt);
            }
        });
        Bottom.add(E4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 310, 60, 60));

        F4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        F4.setText("F");
        F4.setFocusPainted(false);
        F4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F4ActionPerformed(evt);
            }
        });
        Bottom.add(F4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 310, 60, 60));

        Row5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Row5.setForeground(new java.awt.Color(204, 204, 204));
        Row5.setText("5");
        Bottom.add(Row5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, 30, 40));

        A5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        A5.setText("A");
        A5.setFocusPainted(false);
        A5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A5ActionPerformed(evt);
            }
        });
        Bottom.add(A5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 60, 60));

        B5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        B5.setText("B");
        B5.setFocusPainted(false);
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });
        Bottom.add(B5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 60, 60));

        C5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        C5.setText("C");
        C5.setFocusPainted(false);
        C5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C5ActionPerformed(evt);
            }
        });
        Bottom.add(C5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 60, 60));

        D5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        D5.setText("D");
        D5.setFocusPainted(false);
        D5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D5ActionPerformed(evt);
            }
        });
        Bottom.add(D5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 60, 60));

        E5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        E5.setText("E");
        E5.setFocusPainted(false);
        E5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E5ActionPerformed(evt);
            }
        });
        Bottom.add(E5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 380, 60, 60));

        F5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        F5.setText("F");
        F5.setFocusPainted(false);
        F5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F5ActionPerformed(evt);
            }
        });
        Bottom.add(F5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, 60, 60));

        Row6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Row6.setForeground(new java.awt.Color(204, 204, 204));
        Row6.setText("6");
        Bottom.add(Row6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 450, 30, 40));

        A6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        A6.setText("A");
        A6.setFocusPainted(false);
        A6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A6ActionPerformed(evt);
            }
        });
        Bottom.add(A6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 60, 60));

        B6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        B6.setText("B");
        B6.setFocusPainted(false);
        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6ActionPerformed(evt);
            }
        });
        Bottom.add(B6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, 60, 60));

        C6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        C6.setText("C");
        C6.setFocusPainted(false);
        C6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C6ActionPerformed(evt);
            }
        });
        Bottom.add(C6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 60, 60));

        D6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        D6.setText("D");
        D6.setFocusPainted(false);
        D6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D6ActionPerformed(evt);
            }
        });
        Bottom.add(D6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, 60, 60));

        E6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        E6.setText("E");
        E6.setFocusPainted(false);
        E6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E6ActionPerformed(evt);
            }
        });
        Bottom.add(E6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, 60, 60));

        F6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        F6.setText("F");
        F6.setFocusPainted(false);
        F6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F6ActionPerformed(evt);
            }
        });
        Bottom.add(F6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 440, 60, 60));

        Row7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Row7.setForeground(new java.awt.Color(204, 204, 204));
        Row7.setText("7");
        Bottom.add(Row7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 510, 30, 40));

        A7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        A7.setText("A");
        A7.setFocusPainted(false);
        A7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A7ActionPerformed(evt);
            }
        });
        Bottom.add(A7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 500, 60, 60));

        B7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        B7.setText("B");
        B7.setFocusPainted(false);
        B7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B7ActionPerformed(evt);
            }
        });
        Bottom.add(B7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 500, 60, 60));

        C7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        C7.setText("C");
        C7.setFocusPainted(false);
        C7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C7ActionPerformed(evt);
            }
        });
        Bottom.add(C7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, 60, 60));

        D7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        D7.setText("D");
        D7.setFocusPainted(false);
        D7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D7ActionPerformed(evt);
            }
        });
        Bottom.add(D7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 500, 60, 60));

        E7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        E7.setText("E");
        E7.setFocusPainted(false);
        E7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E7ActionPerformed(evt);
            }
        });
        Bottom.add(E7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 500, 60, 60));

        F7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        F7.setText("F");
        F7.setFocusPainted(false);
        F7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F7ActionPerformed(evt);
            }
        });
        Bottom.add(F7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 500, 60, 60));

        javax.swing.GroupLayout RightDoorLayout = new javax.swing.GroupLayout(RightDoor);
        RightDoor.setLayout(RightDoorLayout);
        RightDoorLayout.setHorizontalGroup(
            RightDoorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        RightDoorLayout.setVerticalGroup(
            RightDoorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        Bottom.add(RightDoor, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, -1, -1));

        RightExit.setBackground(new java.awt.Color(52, 79, 88));

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Exit.png"))); // NOI18N

        javax.swing.GroupLayout RightExitLayout = new javax.swing.GroupLayout(RightExit);
        RightExit.setLayout(RightExitLayout);
        RightExitLayout.setHorizontalGroup(
            RightExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightExitLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addContainerGap())
        );
        RightExitLayout.setVerticalGroup(
            RightExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightExitLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        Bottom.add(RightExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 310, -1, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Toilet.png"))); // NOI18N

        javax.swing.GroupLayout Toilet1Layout = new javax.swing.GroupLayout(Toilet1);
        Toilet1.setLayout(Toilet1Layout);
        Toilet1Layout.setHorizontalGroup(
            Toilet1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Toilet1Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        Toilet1Layout.setVerticalGroup(
            Toilet1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Toilet1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        Bottom.add(Toilet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 570, -1, 50));

        OwnerName.setBackground(new java.awt.Color(204, 204, 204));
        OwnerName.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        OwnerName.setForeground(new java.awt.Color(102, 102, 102));
        OwnerName.setText("* The seat plan is for guidance only and not true to scale.");
        Bottom.add(OwnerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 620, 350, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Bottom, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Bottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void A1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1ActionPerformed
        seatButtonSelected("A1");
    }//GEN-LAST:event_A1ActionPerformed

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        seatButtonSelected("B1");
    }//GEN-LAST:event_B1ActionPerformed

    private void C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C1ActionPerformed
        seatButtonSelected("C1");
    }//GEN-LAST:event_C1ActionPerformed

    private void C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C2ActionPerformed
        seatButtonSelected("C2");
    }//GEN-LAST:event_C2ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        seatButtonSelected("B2");
    }//GEN-LAST:event_B2ActionPerformed

    private void A2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2ActionPerformed
        seatButtonSelected("A2");
    }//GEN-LAST:event_A2ActionPerformed

    private void A3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A3ActionPerformed
        seatButtonSelected("A3");
    }//GEN-LAST:event_A3ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        seatButtonSelected("B3");
    }//GEN-LAST:event_B3ActionPerformed

    private void C3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C3ActionPerformed
        seatButtonSelected("C3");
    }//GEN-LAST:event_C3ActionPerformed

    private void C4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C4ActionPerformed
        seatButtonSelected("C4");
    }//GEN-LAST:event_C4ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
        seatButtonSelected("B4");
    }//GEN-LAST:event_B4ActionPerformed

    private void A4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A4ActionPerformed
        seatButtonSelected("A4");
    }//GEN-LAST:event_A4ActionPerformed

    private void A5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A5ActionPerformed
        seatButtonSelected("A5");
    }//GEN-LAST:event_A5ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
        seatButtonSelected("B5");
    }//GEN-LAST:event_B5ActionPerformed

    private void C5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C5ActionPerformed
        seatButtonSelected("C5");
    }//GEN-LAST:event_C5ActionPerformed

    private void C6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C6ActionPerformed
        seatButtonSelected("C6");
    }//GEN-LAST:event_C6ActionPerformed

    private void B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6ActionPerformed
        seatButtonSelected("B6");
    }//GEN-LAST:event_B6ActionPerformed

    private void A6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A6ActionPerformed
        seatButtonSelected("A6");
    }//GEN-LAST:event_A6ActionPerformed

    private void B7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B7ActionPerformed
        seatButtonSelected("B7");
    }//GEN-LAST:event_B7ActionPerformed

    private void A7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A7ActionPerformed
        seatButtonSelected("A7");
    }//GEN-LAST:event_A7ActionPerformed

    private void C7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C7ActionPerformed
        seatButtonSelected("C7");
    }//GEN-LAST:event_C7ActionPerformed

    private void D1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D1ActionPerformed
        seatButtonSelected("D1");
    }//GEN-LAST:event_D1ActionPerformed

    private void E1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1ActionPerformed
        seatButtonSelected("E1");
    }//GEN-LAST:event_E1ActionPerformed

    private void F1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F1ActionPerformed
        seatButtonSelected("F1");
    }//GEN-LAST:event_F1ActionPerformed

    private void F2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F2ActionPerformed
        seatButtonSelected("F2");
    }//GEN-LAST:event_F2ActionPerformed

    private void E2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E2ActionPerformed
        seatButtonSelected("E2");
    }//GEN-LAST:event_E2ActionPerformed

    private void D2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D2ActionPerformed
        seatButtonSelected("D2");
    }//GEN-LAST:event_D2ActionPerformed

    private void D3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D3ActionPerformed
        seatButtonSelected("D3");
    }//GEN-LAST:event_D3ActionPerformed

    private void E3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E3ActionPerformed
        seatButtonSelected("E3");
    }//GEN-LAST:event_E3ActionPerformed

    private void F3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F3ActionPerformed
        seatButtonSelected("F3");
    }//GEN-LAST:event_F3ActionPerformed

    private void F4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F4ActionPerformed
        seatButtonSelected("F4");
    }//GEN-LAST:event_F4ActionPerformed

    private void E4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E4ActionPerformed
        seatButtonSelected("E4");
    }//GEN-LAST:event_E4ActionPerformed

    private void D4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D4ActionPerformed
        seatButtonSelected("D4");
    }//GEN-LAST:event_D4ActionPerformed

    private void D5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D5ActionPerformed
        seatButtonSelected("D5");
    }//GEN-LAST:event_D5ActionPerformed

    private void F5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F5ActionPerformed
        seatButtonSelected("F5");
    }//GEN-LAST:event_F5ActionPerformed

    private void F6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F6ActionPerformed
        seatButtonSelected("F6");
    }//GEN-LAST:event_F6ActionPerformed

    private void E5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E5ActionPerformed
        seatButtonSelected("E5");
    }//GEN-LAST:event_E5ActionPerformed

    private void E6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E6ActionPerformed
        seatButtonSelected("E6");
    }//GEN-LAST:event_E6ActionPerformed

    private void D6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D6ActionPerformed
        seatButtonSelected("D6");
    }//GEN-LAST:event_D6ActionPerformed

    private void D7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D7ActionPerformed
        seatButtonSelected("D7");
    }//GEN-LAST:event_D7ActionPerformed

    private void E7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E7ActionPerformed
        seatButtonSelected("E7");
    }//GEN-LAST:event_E7ActionPerformed

    private void F7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F7ActionPerformed
        seatButtonSelected("F7");
    }//GEN-LAST:event_F7ActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(C_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(C_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(C_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(C_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new C_Book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A1;
    private javax.swing.JButton A2;
    private javax.swing.JButton A3;
    private javax.swing.JButton A4;
    private javax.swing.JButton A5;
    private javax.swing.JButton A6;
    private javax.swing.JButton A7;
    private javax.swing.JLabel Available;
    private javax.swing.JLabel AvailableTextShow;
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JLabel Booked;
    private javax.swing.JLabel BookedTextShow;
    private javax.swing.JPanel Bottom;
    private javax.swing.JButton C1;
    private javax.swing.JButton C2;
    private javax.swing.JButton C3;
    private javax.swing.JButton C4;
    private javax.swing.JButton C5;
    private javax.swing.JButton C6;
    private javax.swing.JButton C7;
    private javax.swing.JLabel CircleDisable1;
    private javax.swing.JLabel CircleDisable2;
    private javax.swing.JLabel CircleDisable3;
    private javax.swing.JLabel CircleDisable4;
    private javax.swing.JLabel CircleEnable;
    private javax.swing.JLabel Copyright;
    private javax.swing.JButton D1;
    private javax.swing.JButton D2;
    private javax.swing.JButton D3;
    private javax.swing.JButton D4;
    private javax.swing.JButton D5;
    private javax.swing.JButton D6;
    private javax.swing.JButton D7;
    private javax.swing.JLabel Date;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JLabel Depart;
    private javax.swing.JLabel DepartureCode;
    private javax.swing.JLabel DepartureName;
    private javax.swing.JLabel DestinationCode;
    private javax.swing.JLabel DestinationName;
    private javax.swing.JButton E1;
    private javax.swing.JButton E2;
    private javax.swing.JButton E3;
    private javax.swing.JButton E4;
    private javax.swing.JButton E5;
    private javax.swing.JButton E6;
    private javax.swing.JButton E7;
    private javax.swing.JButton F1;
    private javax.swing.JButton F2;
    private javax.swing.JButton F3;
    private javax.swing.JButton F4;
    private javax.swing.JButton F5;
    private javax.swing.JButton F6;
    private javax.swing.JButton F7;
    private javax.swing.JLabel From;
    private javax.swing.JPanel Header;
    private javax.swing.JSeparator HorizontalSeperator1;
    private javax.swing.JPanel LeftDoor;
    private javax.swing.JPanel LeftExit;
    private javax.swing.JLabel Line;
    private javax.swing.JLabel NameMaskapai;
    private javax.swing.JLabel OwnerName;
    private javax.swing.JLabel PlaneIcon;
    private javax.swing.JLabel Progress1;
    private javax.swing.JLabel Progress2;
    private javax.swing.JLabel Progress3;
    private javax.swing.JLabel Progress4;
    private javax.swing.JLabel Progress5;
    private javax.swing.JPanel RightDoor;
    private javax.swing.JPanel RightExit;
    private javax.swing.JLabel Row1;
    private javax.swing.JLabel Row2;
    private javax.swing.JLabel Row3;
    private javax.swing.JLabel Row4;
    private javax.swing.JLabel Row5;
    private javax.swing.JLabel Row6;
    private javax.swing.JLabel Row7;
    private javax.swing.JLabel SelectSeat;
    private javax.swing.JLabel Summary;
    private javax.swing.JLabel To;
    private javax.swing.JPanel Toilet;
    private javax.swing.JPanel Toilet1;
    private javax.swing.JSeparator VerticalSeperator1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel27;
    // End of variables declaration//GEN-END:variables
    
    public void setDate(Date selectedDate) {
        this.selectedDate = selectedDate;
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        String dateString = dateFormat.format(selectedDate);
        DateLabel.setText(dateString);
    }
    
    private void summaryText() {
        String availableSeat = Integer.toString(flight.countAvailable());
        String bookedSeat = Integer.toString(42 - flight.countAvailable());
        AvailableTextShow.setText(availableSeat);
        BookedTextShow.setText(bookedSeat);
    }
    
    public void setLabelText(String text) {
        this.text = text;
        DepartureCode.setText(text);        
    }
    
    public void setLabelText1(String text1) {
        this.text1 = text1;
        DepartureName.setText(text1);        
    }
    
    public void setLabelTeks(String teks) {
        this.teks = teks;
        DestinationCode.setText(teks);
    }
    
    public void setLabelTeks1(String teks1) {
        this.teks1 = teks1;
        DestinationName.setText(teks1);    
    }

    private void seatMapShowAvailable() {
        model.Model_Seat mod_seat = new Model_Seat();
        mod_seat.setRoute(text+'-'+teks);
        mod_seat.setDate(selectedDate.toString());
        servis.getSeat(mod_seat);
        ArrayList<String> seats = mod_seat.getSeats();
        int bookedSeat = seats.size();
        int availableSeat = 42 - bookedSeat;
        AvailableTextShow.setText(String.valueOf(availableSeat));
        BookedTextShow.setText(String.valueOf(bookedSeat));
        
        ArrayList<JButton> seatButton = new ArrayList<JButton>();
        seatButton.add(A1);
        seatButton.add(A2);
        seatButton.add(A3);
        seatButton.add(A4);
        seatButton.add(A5);
        seatButton.add(A6);
        seatButton.add(A7);
        seatButton.add(B1);
        seatButton.add(B2);
        seatButton.add(B3);
        seatButton.add(B4);
        seatButton.add(B5);
        seatButton.add(B6);
        seatButton.add(B7);
        seatButton.add(C1);
        seatButton.add(C2);
        seatButton.add(C3);
        seatButton.add(C4);
        seatButton.add(C5);
        seatButton.add(C6);
        seatButton.add(C7);
        seatButton.add(D1);
        seatButton.add(D2);
        seatButton.add(D3);
        seatButton.add(D4);
        seatButton.add(D5);
        seatButton.add(D6);
        seatButton.add(D7);
        seatButton.add(E1);
        seatButton.add(E2);
        seatButton.add(E3);
        seatButton.add(E4);
        seatButton.add(E5);
        seatButton.add(E6);
        seatButton.add(E7);
        seatButton.add(F1);
        seatButton.add(F2);
        seatButton.add(F3);
        seatButton.add(F4);
        seatButton.add(F5);
        seatButton.add(F6);
        seatButton.add(F7);

        ArrayList<String> seatMap = new ArrayList<String>();
        for (char alph = 'A'; alph <= 'F'; alph++) {
            for (int j = 1; j <= 7; j++) {
                String position = alph + "" + j;
                seatMap.add(position);
            }
        }

        for (int j = 0; j < seatButton.size(); j++) {
        String currentSeat = seatMap.get(j);
        if (seats.contains(currentSeat)) {
            seatButton.get(j).setEnabled(false);
        } else {
            seatButton.get(j).setEnabled(true);
        }
        }
    }

    private void seatMapShowBooked() {
        ArrayList<JButton> seatButton = new ArrayList<JButton>();
        seatButton.add(A1);
        seatButton.add(A2);
        seatButton.add(A3);
        seatButton.add(A4);
        seatButton.add(A5);
        seatButton.add(A6);
        seatButton.add(A7);
        seatButton.add(B1);
        seatButton.add(B2);
        seatButton.add(B3);
        seatButton.add(B4);
        seatButton.add(B5);
        seatButton.add(B6);
        seatButton.add(B7);
        seatButton.add(C1);
        seatButton.add(C2);
        seatButton.add(C3);
        seatButton.add(C4);
        seatButton.add(C5);
        seatButton.add(C6);
        seatButton.add(C7);
        seatButton.add(D1);
        seatButton.add(D2);
        seatButton.add(D3);
        seatButton.add(D4);
        seatButton.add(D5);
        seatButton.add(D6);
        seatButton.add(D7);
        seatButton.add(E1);
        seatButton.add(E2);
        seatButton.add(E3);
        seatButton.add(E4);
        seatButton.add(E5);
        seatButton.add(E6);
        seatButton.add(E7);
        seatButton.add(F1);
        seatButton.add(F2);
        seatButton.add(F3);
        seatButton.add(F4);
        seatButton.add(F5);
        seatButton.add(F6);
        seatButton.add(F7);

        ArrayList<String> seatMap = new ArrayList<String>();
        for (char alph = 'A'; alph <= 'F'; alph++) {
            for (int j = 1; j <= 7; j++) {
                String position = alph + "" + j;
                seatMap.add(position);
            }
        }

        for (int j = 0; j <= 41; j++) {
            if (flight.getSeatStatus(seatMap.get(j)) == true) {
                (seatButton.get(j)).setEnabled(false);
            } else {
                (seatButton.get(j)).setEnabled(true);
            }
        }
    }

    public void seatButtonSelected(String buttonSelected) {
        String position = buttonSelected;
            System.out.println("BOOKING process of " + position + " starred.");
            D_Passenger D_Passenger = new D_Passenger(position, modelLogin);
            D_Passenger.setDate(selectedDate);
            D_Passenger.setLabelText(text);
            D_Passenger.setLabelText1(text1);
            D_Passenger.setLabelTeks(teks);
            D_Passenger.setLabelTeks1(teks1);
            D_Passenger.setVisible(true);
            D_Passenger.revalidate();
            dispose();
    }
}