/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Customer;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Model_Login;

/**
 *
 * @author harlan
 */
public class D_Passenger extends javax.swing.JFrame {
    private Model_Login modelLogin;
    private Date selectedDate;
    private String text;
    private String text1;
    private String teks;
    private String teks1;
    /**
     * Creates new form RegisterForm
     */
    public D_Passenger() {
        initComponents();
    }
    
    public D_Passenger(String seat, Model_Login modelLogin) {
        this.modelLogin = modelLogin;
        initComponents();
        SeatTextShow.setText(seat);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        NameMaskapai1 = new javax.swing.JLabel();
        CircleDisable1 = new javax.swing.JLabel();
        CircleDisable2 = new javax.swing.JLabel();
        CircleEnable3 = new javax.swing.JLabel();
        CircleDisable4 = new javax.swing.JLabel();
        CircleDisable5 = new javax.swing.JLabel();
        Line = new javax.swing.JLabel();
        Progress1 = new javax.swing.JLabel();
        Progress2 = new javax.swing.JLabel();
        Progress3 = new javax.swing.JLabel();
        Progress4 = new javax.swing.JLabel();
        Progress5 = new javax.swing.JLabel();
        Bottom = new javax.swing.JPanel();
        Passenger = new javax.swing.JLabel();
        Passengers = new javax.swing.JLabel();
        FirstNameText = new javax.swing.JLabel();
        FirstNameField = new javax.swing.JTextField();
        WarningText1 = new javax.swing.JLabel();
        LastNameText = new javax.swing.JLabel();
        LastNameField = new javax.swing.JTextField();
        WarningText2 = new javax.swing.JLabel();
        PassportNoText = new javax.swing.JLabel();
        PassportNoField = new javax.swing.JTextField();
        WarningText3 = new javax.swing.JLabel();
        Copyright = new javax.swing.JLabel();
        VerticalSeperator1 = new javax.swing.JSeparator();
        From = new javax.swing.JLabel();
        DepartureCode = new javax.swing.JLabel();
        DepartureName = new javax.swing.JLabel();
        PlaneIcon = new javax.swing.JLabel();
        To = new javax.swing.JLabel();
        DestinationCode = new javax.swing.JLabel();
        DestinationName = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        DateLabel = new javax.swing.JLabel();
        Seat = new javax.swing.JLabel();
        Seats = new javax.swing.JPanel();
        SeatTextShow = new javax.swing.JLabel();
        HorizontalSeperator1 = new javax.swing.JSeparator();
        BackButton = new javax.swing.JButton();
        ContinueButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nine Airlines (Passenger)");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(0, 153, 255));
        Header.setToolTipText("");
        Header.setPreferredSize(new java.awt.Dimension(900, 150));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NameMaskapai1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NameMaskapai1.setForeground(new java.awt.Color(255, 255, 255));
        NameMaskapai1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/NameMaskapai.png"))); // NOI18N
        Header.add(NameMaskapai1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        CircleDisable1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CircleDisable.png"))); // NOI18N
        Header.add(CircleDisable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, -1, -1));

        CircleDisable2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CircleDisable.png"))); // NOI18N
        Header.add(CircleDisable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, -1, -1));

        CircleEnable3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Circle.png"))); // NOI18N
        Header.add(CircleEnable3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, -1, -1));

        CircleDisable4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CircleDisable.png"))); // NOI18N
        Header.add(CircleDisable4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 70, -1, -1));

        CircleDisable5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CircleDisable.png"))); // NOI18N
        Header.add(CircleDisable5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 70, -1, -1));

        Line.setForeground(new java.awt.Color(21, 30, 158));
        Line.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Line.png"))); // NOI18N
        Header.add(Line, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 65, 300, 30));

        Progress1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Progress1.setForeground(new java.awt.Color(21, 30, 158));
        Progress1.setText("Destination");
        Header.add(Progress1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, -1, -1));

        Progress2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Progress2.setForeground(new java.awt.Color(21, 30, 158));
        Progress2.setText("Seats");
        Header.add(Progress2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, -1, -1));

        Progress3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Progress3.setForeground(new java.awt.Color(255, 255, 255));
        Progress3.setText("Passenger");
        Header.add(Progress3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, -1, -1));

        Progress4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Progress4.setForeground(new java.awt.Color(21, 30, 158));
        Progress4.setText("Bill");
        Header.add(Progress4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, -1, -1));

        Progress5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Progress5.setForeground(new java.awt.Color(21, 30, 158));
        Progress5.setText("Confirm");
        Header.add(Progress5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 50, -1, -1));

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Bottom.setBackground(new java.awt.Color(255, 255, 255));
        Bottom.setPreferredSize(new java.awt.Dimension(900, 650));
        Bottom.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Passenger.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        Passenger.setText("Passenger Details");
        Bottom.add(Passenger, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 340, 50));

        Passengers.setBackground(new java.awt.Color(204, 204, 204));
        Passengers.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Passengers.setForeground(new java.awt.Color(102, 102, 102));
        Passengers.setText("Passenger details must match the government-issued photo ID.");
        Bottom.add(Passengers, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 440, 20));

        FirstNameText.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        FirstNameText.setText("First Name");
        Bottom.add(FirstNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, 50));

        FirstNameField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        FirstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameFieldActionPerformed(evt);
            }
        });
        Bottom.add(FirstNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 390, 40));

        WarningText1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        WarningText1.setForeground(new java.awt.Color(207, 0, 15));
        Bottom.add(WarningText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 210, 50));

        LastNameText.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        LastNameText.setText("Last Name");
        Bottom.add(LastNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, 50));

        LastNameField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Bottom.add(LastNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 390, 40));

        WarningText2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        WarningText2.setForeground(new java.awt.Color(207, 0, 15));
        Bottom.add(WarningText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 210, 50));

        PassportNoText.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        PassportNoText.setText("Passport No.");
        Bottom.add(PassportNoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, -1, 50));

        PassportNoField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        PassportNoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassportNoFieldActionPerformed(evt);
            }
        });
        Bottom.add(PassportNoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 390, 40));

        WarningText3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        WarningText3.setForeground(new java.awt.Color(207, 0, 15));
        Bottom.add(WarningText3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 230, 50));

        Copyright.setBackground(new java.awt.Color(204, 204, 204));
        Copyright.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Copyright.setForeground(new java.awt.Color(102, 102, 102));
        Copyright.setText("© 2024 Nine Airlines.");
        Bottom.add(Copyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, 210, -1));

        VerticalSeperator1.setBackground(new java.awt.Color(0, 0, 0));
        VerticalSeperator1.setForeground(new java.awt.Color(0, 0, 0));
        VerticalSeperator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Bottom.add(VerticalSeperator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 10, 500));

        From.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        From.setForeground(new java.awt.Color(102, 102, 102));
        From.setText("FROM");
        Bottom.add(From, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, -1, 12));

        DepartureCode.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        DepartureCode.setForeground(new java.awt.Color(0, 153, 255));
        DepartureCode.setText("---");
        Bottom.add(DepartureCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, -1, 35));

        DepartureName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        DepartureName.setForeground(new java.awt.Color(102, 102, 102));
        DepartureName.setText("-----");
        Bottom.add(DepartureName, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, 80, 20));

        PlaneIcon.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        PlaneIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BlackPlane.png"))); // NOI18N
        Bottom.add(PlaneIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(695, 170, 40, -1));

        To.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        To.setForeground(new java.awt.Color(102, 102, 102));
        To.setText("TO");
        Bottom.add(To, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 150, -1, 12));

        DestinationCode.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        DestinationCode.setForeground(new java.awt.Color(0, 153, 255));
        DestinationCode.setText("---");
        Bottom.add(DestinationCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 170, -1, 35));

        DestinationName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        DestinationName.setForeground(new java.awt.Color(102, 102, 102));
        DestinationName.setText("-----");
        Bottom.add(DestinationName, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 210, 90, 20));

        Date.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Date.setForeground(new java.awt.Color(102, 102, 102));
        Date.setText("DATE");
        Bottom.add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 80, 12));

        DateLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        DateLabel.setForeground(new java.awt.Color(0, 153, 255));
        DateLabel.setText("-- ---");
        Bottom.add(DateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, -1, 30));

        Seat.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Seat.setForeground(new java.awt.Color(102, 102, 102));
        Seat.setText("SEAT");
        Bottom.add(Seat, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, 70, 20));

        Seats.setBackground(new java.awt.Color(0, 153, 255));

        SeatTextShow.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        SeatTextShow.setForeground(new java.awt.Color(255, 255, 255));
        SeatTextShow.setText("--");

        javax.swing.GroupLayout SeatsLayout = new javax.swing.GroupLayout(Seats);
        Seats.setLayout(SeatsLayout);
        SeatsLayout.setHorizontalGroup(
            SeatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeatsLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(SeatTextShow)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        SeatsLayout.setVerticalGroup(
            SeatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeatsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SeatTextShow, javax.swing.GroupLayout.PREFERRED_SIZE, 38, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );

        Bottom.add(Seats, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 330, 100, 50));
        Bottom.add(HorizontalSeperator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, 280, 10));

        BackButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BackButton.setText("BACK");
        BackButton.setFocusPainted(false);
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        Bottom.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, 100, 60));

        ContinueButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ContinueButton.setText("CONTINUE");
        ContinueButton.setFocusPainted(false);
        ContinueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueButtonActionPerformed(evt);
            }
        });
        Bottom.add(ContinueButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 460, 160, 60));

        getContentPane().add(Bottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FirstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameFieldActionPerformed

    private void PassportNoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassportNoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassportNoFieldActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        this.setVisible(false);
            C_Book C_Book = new C_Book(selectedDate, text, teks, modelLogin);
            C_Book.setDate(selectedDate);
            C_Book.setLabelText(text);
            C_Book.setLabelText1(text1);
            C_Book.setLabelTeks(teks);
            C_Book.setLabelTeks1(teks1);
            C_Book.setVisible(true);
            C_Book.revalidate();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void ContinueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueButtonActionPerformed
        if (FirstNameField.getText().isEmpty() && LastNameField.getText().isEmpty() && PassportNoField.getText().isEmpty()) {
            WarningText1.setText("* First Name is Required");
            WarningText2.setText("* Last Name is Required");
            WarningText3.setText("* Passport No. is Required");
        } else if (FirstNameField.getText().isEmpty() && LastNameField.getText().isEmpty()) {
            WarningText1.setText("* First Name is Required");
            WarningText2.setText("* Last Name is Required");
            WarningText3.setText("");
        } else if (FirstNameField.getText().isEmpty() && PassportNoField.getText().isEmpty()) {
            WarningText1.setText("* First Name is Required");
            WarningText2.setText("");
            WarningText3.setText("* Passport No. is Required");
        } else if (LastNameField.getText().isEmpty() && PassportNoField.getText().isEmpty()) {
            WarningText1.setText("");
            WarningText2.setText("* Last Name is Required");
            WarningText3.setText("* Passport No. is Required");
        } else if (FirstNameField.getText().isEmpty()) {
            WarningText1.setText("* First Name is Required");
            WarningText2.setText("");
            WarningText3.setText("");
        } else if (LastNameField.getText().isEmpty()) {
            WarningText1.setText("");
            WarningText2.setText("* Last Name is Required");
            WarningText3.setText("");
        } else if (PassportNoField.getText().isEmpty()) {
            WarningText1.setText("");
            WarningText2.setText("");
            WarningText3.setText("* Passport No. is Required");
        } else {
            String firstName = FirstNameField.getText();
            String lastName = LastNameField.getText();
            String passportNo = PassportNoField.getText();
            String seat = SeatTextShow.getText();
            String from = DepartureCode.getText();
            String to = DestinationCode.getText();
            String fromDetail = DepartureName.getText();
            String toDetail = DestinationName.getText();
            
            JOptionPane.showMessageDialog(null, "Seats retrieved successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            E_Bill E_Bill = new E_Bill(seat, firstName, lastName, passportNo, from, to, fromDetail, toDetail, selectedDate, modelLogin);
            E_Bill.setVisible(true);
            E_Bill.revalidate();
            dispose();
        }
    }//GEN-LAST:event_ContinueButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(D_Passenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(D_Passenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(D_Passenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(D_Passenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new D_Passenger().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JPanel Bottom;
    private javax.swing.JLabel CircleDisable1;
    private javax.swing.JLabel CircleDisable2;
    private javax.swing.JLabel CircleDisable4;
    private javax.swing.JLabel CircleDisable5;
    private javax.swing.JLabel CircleEnable3;
    private javax.swing.JButton ContinueButton;
    private javax.swing.JLabel Copyright;
    private javax.swing.JLabel Date;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JLabel DepartureCode;
    private javax.swing.JLabel DepartureName;
    private javax.swing.JLabel DestinationCode;
    private javax.swing.JLabel DestinationName;
    private javax.swing.JTextField FirstNameField;
    private javax.swing.JLabel FirstNameText;
    private javax.swing.JLabel From;
    private javax.swing.JPanel Header;
    private javax.swing.JSeparator HorizontalSeperator1;
    private javax.swing.JTextField LastNameField;
    private javax.swing.JLabel LastNameText;
    private javax.swing.JLabel Line;
    private javax.swing.JLabel NameMaskapai1;
    private javax.swing.JLabel Passenger;
    private javax.swing.JLabel Passengers;
    private javax.swing.JTextField PassportNoField;
    private javax.swing.JLabel PassportNoText;
    private javax.swing.JLabel PlaneIcon;
    private javax.swing.JLabel Progress1;
    private javax.swing.JLabel Progress2;
    private javax.swing.JLabel Progress3;
    private javax.swing.JLabel Progress4;
    private javax.swing.JLabel Progress5;
    private javax.swing.JLabel Seat;
    private javax.swing.JLabel SeatTextShow;
    private javax.swing.JPanel Seats;
    private javax.swing.JLabel To;
    private javax.swing.JSeparator VerticalSeperator1;
    private javax.swing.JLabel WarningText1;
    private javax.swing.JLabel WarningText2;
    private javax.swing.JLabel WarningText3;
    // End of variables declaration//GEN-END:variables

    public void setDate(Date selectedDate) {
        this.selectedDate = selectedDate;
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        String dateString = dateFormat.format(selectedDate);
        DateLabel.setText(dateString);
    }
    
    public void setLabelText(String text) {
        this.text = text;
        DepartureCode.setText(text);
        
    }
    
    public void setLabelText1(String text1) {
        this.text1 = text1;
        DepartureName.setText(text1);
        
    }
    
    public void setLabelTeks(String teks) {
        this.teks = teks;
        DestinationCode.setText(teks);
        
    }
    
    public void setLabelTeks1(String teks1) {
        this.teks1 = teks1;
        DestinationName.setText(teks1);
        
    }
    
}