/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Customer;

import dao.DAO_Booking;
import java.util.Date;
import javax.swing.JOptionPane;
import service.Service_Booking;
import model.Model_Booking;
import model.Model_Login;

/**
 *
 * @author harlan
 */
public class E_Bill extends javax.swing.JFrame {
    private String seat;
    private String firstName;
    private String lastName;
    private String passportNo;
    private Double amount;
    private Date selectedDate;
    private String from;
    private String to;
    private String fromDetail;
    private String toDetail;
    
    private Service_Booking servis = new DAO_Booking();
    private Model_Login modelLogin;

    /**
     * Creates new form E_Bill
     */
    public E_Bill() {
        initComponents();
    }
    
    public E_Bill(String seat, String firstName, String lastName, String passportNo, String from, String to, String fromDetail, String toDetail, Date selectedDate, Model_Login modelLogin) {
        this.seat = seat;
        this.modelLogin = modelLogin;
        this.from = from;
        this.to = to;
        this.fromDetail = fromDetail;
        this.toDetail = toDetail;
        this.firstName = firstName;
        this.lastName = lastName;
        this.passportNo = passportNo;
        this.selectedDate = selectedDate;
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        NameMaskapai = new javax.swing.JLabel();
        CircleEnable = new javax.swing.JLabel();
        CircleDisable1 = new javax.swing.JLabel();
        CircleDisable2 = new javax.swing.JLabel();
        CircleDisable3 = new javax.swing.JLabel();
        CircleDisable4 = new javax.swing.JLabel();
        Line = new javax.swing.JLabel();
        Progress1 = new javax.swing.JLabel();
        Progress2 = new javax.swing.JLabel();
        Progress3 = new javax.swing.JLabel();
        Progress4 = new javax.swing.JLabel();
        Progress5 = new javax.swing.JLabel();
        Bottom = new javax.swing.JPanel();
        PurchaseDetaill = new javax.swing.JLabel();
        Item = new javax.swing.JLabel();
        Item1 = new javax.swing.JLabel();
        Quantity = new javax.swing.JLabel();
        Quantity1 = new javax.swing.JLabel();
        PricePerUnit = new javax.swing.JLabel();
        PricePerUnit1 = new javax.swing.JLabel();
        Tax = new javax.swing.JLabel();
        Tax1 = new javax.swing.JLabel();
        SubTotal = new javax.swing.JLabel();
        SubTotal1 = new javax.swing.JLabel();
        VerticalSeperator1 = new javax.swing.JSeparator();
        HorizontalSeperator1 = new javax.swing.JSeparator();
        Total = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lb_amount = new javax.swing.JLabel();
        Payment = new javax.swing.JPanel();
        Payments = new javax.swing.JLabel();
        Item2 = new javax.swing.JLabel();
        Quantity2 = new javax.swing.JLabel();
        PricePerUnit2 = new javax.swing.JLabel();
        Tax2 = new javax.swing.JLabel();
        PricePerUnit3 = new javax.swing.JLabel();
        Item3 = new javax.swing.JLabel();
        Quantity3 = new javax.swing.JLabel();
        PricePerUnit4 = new javax.swing.JLabel();
        Tax3 = new javax.swing.JLabel();
        Tax4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        PricePerUnit5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Pay1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Header.setBackground(new java.awt.Color(0, 153, 255));
        Header.setToolTipText("");
        Header.setPreferredSize(new java.awt.Dimension(900, 150));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NameMaskapai.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NameMaskapai.setForeground(new java.awt.Color(255, 255, 255));
        NameMaskapai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/NameMaskapai.png"))); // NOI18N
        Header.add(NameMaskapai, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        CircleEnable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CircleDisable.png"))); // NOI18N
        Header.add(CircleEnable, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, -1, -1));

        CircleDisable1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CircleDisable.png"))); // NOI18N
        Header.add(CircleDisable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, -1, -1));

        CircleDisable2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CircleDisable.png"))); // NOI18N
        Header.add(CircleDisable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, -1, -1));

        CircleDisable3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Circle.png"))); // NOI18N
        Header.add(CircleDisable3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, -1, -1));

        CircleDisable4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CircleDisable.png"))); // NOI18N
        Header.add(CircleDisable4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 70, -1, -1));

        Line.setForeground(new java.awt.Color(21, 30, 158));
        Line.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Line.png"))); // NOI18N
        Header.add(Line, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 65, 300, 30));

        Progress1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Progress1.setForeground(new java.awt.Color(21, 30, 158));
        Progress1.setText("Destination");
        Header.add(Progress1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, -1, -1));

        Progress2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Progress2.setForeground(new java.awt.Color(21, 30, 158));
        Progress2.setText("Seats");
        Header.add(Progress2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, -1, -1));

        Progress3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Progress3.setForeground(new java.awt.Color(21, 30, 158));
        Progress3.setText("Passenger");
        Header.add(Progress3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, -1, -1));

        Progress4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Progress4.setForeground(new java.awt.Color(255, 255, 255));
        Progress4.setText("Bill");
        Header.add(Progress4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, -1, -1));

        Progress5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Progress5.setForeground(new java.awt.Color(21, 30, 158));
        Progress5.setText("Confirm");
        Header.add(Progress5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 50, -1, -1));

        Bottom.setBackground(new java.awt.Color(255, 255, 255));
        Bottom.setPreferredSize(new java.awt.Dimension(450, 650));
        Bottom.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PurchaseDetaill.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        PurchaseDetaill.setText("PURCHASE DETAIL");
        Bottom.add(PurchaseDetaill, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 60));

        Item.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Item.setForeground(new java.awt.Color(102, 102, 102));
        Item.setText("Item");
        Bottom.add(Item, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 100, 20));

        Item1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Item1.setForeground(new java.awt.Color(102, 102, 102));
        Item1.setText(":");
        Bottom.add(Item1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 10, 20));

        Quantity.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Quantity.setForeground(new java.awt.Color(102, 102, 102));
        Quantity.setText("Quantity");
        Bottom.add(Quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 100, 20));

        Quantity1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Quantity1.setForeground(new java.awt.Color(102, 102, 102));
        Quantity1.setText(":");
        Bottom.add(Quantity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 10, 20));

        PricePerUnit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        PricePerUnit.setForeground(new java.awt.Color(102, 102, 102));
        PricePerUnit.setText("Price/Unit");
        Bottom.add(PricePerUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 100, 20));

        PricePerUnit1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        PricePerUnit1.setForeground(new java.awt.Color(102, 102, 102));
        PricePerUnit1.setText(":");
        Bottom.add(PricePerUnit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 10, 20));

        Tax.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Tax.setForeground(new java.awt.Color(102, 102, 102));
        Tax.setText("Tax");
        Bottom.add(Tax, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 100, 20));

        Tax1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Tax1.setForeground(new java.awt.Color(102, 102, 102));
        Tax1.setText(":");
        Bottom.add(Tax1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 20, 20));

        SubTotal.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        SubTotal.setForeground(new java.awt.Color(102, 102, 102));
        SubTotal.setText("SUB TOTAL");
        Bottom.add(SubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 150, 20));

        SubTotal1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        SubTotal1.setForeground(new java.awt.Color(102, 102, 102));
        SubTotal1.setText(":");
        Bottom.add(SubTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 20, 20));

        VerticalSeperator1.setBackground(new java.awt.Color(0, 0, 0));
        VerticalSeperator1.setForeground(new java.awt.Color(0, 0, 0));
        VerticalSeperator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Bottom.add(VerticalSeperator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 10, 590));
        Bottom.add(HorizontalSeperator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 350, 10));

        Total.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Total.setText("Total");
        Total.setFocusPainted(false);
        Total.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TotalMouseClicked(evt);
            }
        });
        Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalActionPerformed(evt);
            }
        });
        Bottom.add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 160, 40));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Bottom.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 160, 20));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Bottom.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 160, 20));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Bottom.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 160, 20));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Bottom.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 160, 20));

        lb_amount.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Bottom.add(lb_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 365, 180, 30));

        Payment.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Payments.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        Payments.setText("PAYMENT");
        Payments.setPreferredSize(new java.awt.Dimension(185, 45));
        Payment.add(Payments, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 30, -1, 60));

        Item2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Item2.setForeground(new java.awt.Color(102, 102, 102));
        Item2.setText("Username");
        Payment.add(Item2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 100, 20));

        Quantity2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Quantity2.setForeground(new java.awt.Color(102, 102, 102));
        Quantity2.setText("No Card");
        Payment.add(Quantity2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 100, 20));

        PricePerUnit2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        PricePerUnit2.setForeground(new java.awt.Color(102, 102, 102));
        PricePerUnit2.setText("OTP");
        Payment.add(PricePerUnit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 100, 20));

        Tax2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Tax2.setForeground(new java.awt.Color(102, 102, 102));
        Tax2.setText("Expiry");
        Payment.add(Tax2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 100, 20));

        PricePerUnit3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        PricePerUnit3.setForeground(new java.awt.Color(102, 102, 102));
        PricePerUnit3.setText("CVV");
        Payment.add(PricePerUnit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 100, 20));

        Item3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Item3.setForeground(new java.awt.Color(102, 102, 102));
        Item3.setText(":");
        Payment.add(Item3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 10, 20));

        Quantity3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Quantity3.setForeground(new java.awt.Color(102, 102, 102));
        Quantity3.setText(":");
        Payment.add(Quantity3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 10, 20));

        PricePerUnit4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        PricePerUnit4.setForeground(new java.awt.Color(102, 102, 102));
        PricePerUnit4.setText("/");
        Payment.add(PricePerUnit4, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 310, 10, 20));

        Tax3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Tax3.setForeground(new java.awt.Color(102, 102, 102));
        Tax3.setText(":");
        Payment.add(Tax3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 10, 20));

        Tax4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Tax4.setForeground(new java.awt.Color(102, 102, 102));
        Tax4.setText(":");
        Payment.add(Tax4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 10, 20));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        Payment.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 80, -1));

        jTextField2.setPreferredSize(new java.awt.Dimension(80, 23));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        Payment.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        Payment.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 180, -1));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        Payment.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 180, -1));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        Payment.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 180, -1));

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        Payment.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 180, -1));

        jTextField7.setPreferredSize(new java.awt.Dimension(80, 23));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        Payment.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, -1, -1));

        PricePerUnit5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        PricePerUnit5.setForeground(new java.awt.Color(102, 102, 102));
        PricePerUnit5.setText(":");
        Payment.add(PricePerUnit5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 10, 20));

        jButton1.setText("Generate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Payment.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, -1, -1));

        Pay1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Pay1.setText("Pay");
        Pay1.setFocusPainted(false);
        Pay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pay1ActionPerformed(evt);
            }
        });
        Payment.add(Pay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 160, 40));

        Bottom.add(Payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 370, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Bottom, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Bottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalActionPerformed
        double Singapore = 1500000;
        double Malaysia = 1250000;
        double Jakarta = 1000000;
        double [] cost = new double [20];
        double tax = 11;
        
        if (from.equals("CGK")){
                if (to.equals("SIN")){
                    jLabel1.setText("Ticket CGK - SIN");
                    jLabel2.setText("1");
                    String sppu = String.format("Rp%.2f", Singapore);
                    jLabel3.setText(sppu);
                    cost[0] = (Singapore * tax / 100);
                    String stax = String.format("Rp%.2f", cost[0]);
                    jLabel4.setText(stax);
                    String stotal = String.format("Rp%.2f", cost[0] + Singapore);
                    lb_amount.setText(stotal);
                }else if (to.equals("KUL")){
                    jLabel1.setText("Ticket CGK - KUL");
                    jLabel2.setText("1");
                    String mppu = String.format("Rp%.2f", Malaysia);
                    jLabel3.setText(mppu);
                    cost[0] = (Malaysia * tax / 100);
                    String mtax = String.format("Rp%.2f", cost[0]);
                    jLabel4.setText(mtax);
                    String mtotal = String.format("Rp%.2f", cost[0] + Malaysia);
                    lb_amount.setText(mtotal);
                }
        }
        
        if (from.equals("SIN")){
                if (to.equals("CGK")){
                    jLabel1.setText("Ticket SIN - CGK");
                    jLabel2.setText("1");
                    String jppu = String.format("Rp%.2f", Jakarta);
                    jLabel3.setText(jppu);
                    cost[0] = (Jakarta * tax / 100);
                    String jtax = String.format("Rp%.2f", cost[0]);
                    jLabel4.setText(jtax);
                    String jtotal = String.format("Rp%.2f", cost[0] + Jakarta);
                    lb_amount.setText(jtotal);
                }else if (to.equals("KUL")){
                    jLabel1.setText("Ticket SIN - KUL");
                    jLabel2.setText("1");
                    String mppu = String.format("Rp%.2f", Malaysia);
                    jLabel3.setText(mppu);
                    cost[0] = (Malaysia * tax / 100);
                    String mtax = String.format("Rp%.2f", cost[0]);
                    jLabel4.setText(mtax);
                    String mtotal = String.format("Rp%.2f", cost[0] + Malaysia);
                    lb_amount.setText(mtotal);
                }
        }
        
        if (from.equals("KUL")){
                if (to.equals("CGK")){
                    jLabel1.setText("Ticket KUL - CGK");
                    jLabel2.setText("1");
                    String jppu = String.format("Rp%.2f", Jakarta);
                    jLabel3.setText(jppu);
                    cost[0] = (Jakarta * tax / 100);
                    String jtax = String.format("Rp%.2f", cost[0]);
                    jLabel4.setText(jtax);
                    String jtotal = String.format("Rp%.2f", cost[0] + Jakarta);
                    lb_amount.setText(jtotal);
                }else if (to.equals("SIN")){
                    jLabel1.setText("Ticket KUL - SIN");
                    jLabel2.setText("1");
                    String sppu = String.format("Rp%.2f", Singapore);
                    jLabel3.setText(sppu);
                    cost[0] = (Singapore * tax / 100);
                    String stax = String.format("Rp%.2f", cost[0]);
                    jLabel4.setText(stax);
                    String stotal = String.format("Rp%.2f", cost[0] + Singapore);
                    lb_amount.setText(stotal);
                }
        }          
    }//GEN-LAST:event_TotalActionPerformed

    private void TotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TotalMouseClicked
        // TODO add your handling code here:
                               
    }//GEN-LAST:event_TotalMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if((jTextField3.getText().length()==12) && (jTextField4.getText().length()==3) && (jTextField7.getText().length()==2) && (jTextField2.getText().length()==2)){
            int nume;
        String l ="";
        nume =1204+(int)(Math.random()*423);
        l+= nume+120;
        jTextField1.setText(l);   
    }else{
        JOptionPane.showConfirmDialog(null,"Enter correct Payment details","Ticket Booking", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Pay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pay1ActionPerformed
        // TODO add your handling code here:
        prosesBooking();
        F_Confirm F_Confirm = new F_Confirm(seat, firstName, lastName, passportNo, modelLogin);
        F_Confirm.setDate(selectedDate);
        F_Confirm.setLabelText(from);
        F_Confirm.setLabelText1(fromDetail);
        F_Confirm.setLabelTeks(to);
        F_Confirm.setLabelTeks1(toDetail);
        F_Confirm.setVisible(true);
        F_Confirm.revalidate();

        dispose();
    }//GEN-LAST:event_Pay1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(E_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(E_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(E_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(E_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new E_Bill().setVisible(true);
            }
        });
    }
    
    private void prosesBooking(){
        String route = from+'-'+to;
        model.Model_Booking mod_book = new Model_Booking();
        mod_book.setFname(firstName);
        mod_book.setLname(lastName);
        mod_book.setNpassport(passportNo);
        mod_book.setRoute(route);
        mod_book.setBook(seat);
        mod_book.setDate(selectedDate.toString());
        String amountt = lb_amount.getText();
        amountt = amountt.replaceAll("[^\\d.]", "");
        double amountDouble = Double.parseDouble(amountt);
        mod_book.setAmount(amountDouble);
        servis.insertBooking(mod_book);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bottom;
    private javax.swing.JLabel CircleDisable1;
    private javax.swing.JLabel CircleDisable2;
    private javax.swing.JLabel CircleDisable3;
    private javax.swing.JLabel CircleDisable4;
    private javax.swing.JLabel CircleEnable;
    private javax.swing.JPanel Header;
    private javax.swing.JSeparator HorizontalSeperator1;
    private javax.swing.JLabel Item;
    private javax.swing.JLabel Item1;
    private javax.swing.JLabel Item2;
    private javax.swing.JLabel Item3;
    private javax.swing.JLabel Line;
    private javax.swing.JLabel NameMaskapai;
    private javax.swing.JButton Pay1;
    private javax.swing.JPanel Payment;
    private javax.swing.JLabel Payments;
    private javax.swing.JLabel PricePerUnit;
    private javax.swing.JLabel PricePerUnit1;
    private javax.swing.JLabel PricePerUnit2;
    private javax.swing.JLabel PricePerUnit3;
    private javax.swing.JLabel PricePerUnit4;
    private javax.swing.JLabel PricePerUnit5;
    private javax.swing.JLabel Progress1;
    private javax.swing.JLabel Progress2;
    private javax.swing.JLabel Progress3;
    private javax.swing.JLabel Progress4;
    private javax.swing.JLabel Progress5;
    private javax.swing.JLabel PurchaseDetaill;
    private javax.swing.JLabel Quantity;
    private javax.swing.JLabel Quantity1;
    private javax.swing.JLabel Quantity2;
    private javax.swing.JLabel Quantity3;
    private javax.swing.JLabel SubTotal;
    private javax.swing.JLabel SubTotal1;
    private javax.swing.JLabel Tax;
    private javax.swing.JLabel Tax1;
    private javax.swing.JLabel Tax2;
    private javax.swing.JLabel Tax3;
    private javax.swing.JLabel Tax4;
    private javax.swing.JButton Total;
    private javax.swing.JSeparator VerticalSeperator1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel lb_amount;
    // End of variables declaration//GEN-END:variables
}
