/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Customer;

import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import model.Model_Login;

/**
 *
 * @author harlan
 */
public class F_Confirm extends javax.swing.JFrame {
    private Model_Login modelLogin;
    /**
     * Creates new form Confirmation
     */
    public F_Confirm() {
        initComponents();
    }

    public F_Confirm(String seat, String firstName, String lastName, String passportNo, Model_Login modelLogin) {
        initComponents();
        this.modelLogin = modelLogin;
        SeatTextShow.setText(seat);
        FirstNameShow.setText(firstName);
        LastNameShow.setText(lastName);
        PassportNoShow.setText(passportNo);
        boardingPassPrinter(seat, firstName, lastName, passportNo);
        C_Book.flight.bookSeat(seat, firstName, lastName, passportNo);
    }
    
    public static void boardingPassPrinter(String seat, String firstName, String lastName, String passportNo) {
        try {
            FileWriter w = new FileWriter(seat + "_broadingPass.txt");
            w.write("AIRLINES AIRLINES BOARDING PASS\r\n");  
            w.write("\r\n");
            w.write("Seat :  " + seat + "\r\n");
            w.write("Name :  " + firstName + " " + lastName + "\r\n");
            w.write("Passport No. :  " + passportNo + "\r\n");
            w.write("\r\nPlease remember your data for flight cancellation. \r\n© 2024 Nine Airlines.");    
            w.close();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        NameMaskapai1 = new javax.swing.JLabel();
        CircleDisable1 = new javax.swing.JLabel();
        CircleDisable2 = new javax.swing.JLabel();
        CircleDisable3 = new javax.swing.JLabel();
        CircleDisable4 = new javax.swing.JLabel();
        CircleEnable5 = new javax.swing.JLabel();
        Line = new javax.swing.JLabel();
        Progress1 = new javax.swing.JLabel();
        Progress2 = new javax.swing.JLabel();
        Progress3 = new javax.swing.JLabel();
        Progress4 = new javax.swing.JLabel();
        Progress5 = new javax.swing.JLabel();
        Bottom = new javax.swing.JPanel();
        BookingSummary = new javax.swing.JLabel();
        Please = new javax.swing.JLabel();
        FirstName = new javax.swing.JLabel();
        FirstNameShow = new javax.swing.JLabel();
        LastName = new javax.swing.JLabel();
        LastNameShow = new javax.swing.JLabel();
        PassportNo = new javax.swing.JLabel();
        PassportNoShow = new javax.swing.JLabel();
        From = new javax.swing.JLabel();
        DepartureCode = new javax.swing.JLabel();
        DepartureName = new javax.swing.JLabel();
        PlaneIcon = new javax.swing.JLabel();
        To = new javax.swing.JLabel();
        DestinationCode = new javax.swing.JLabel();
        DestinationName = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        DateLabel = new javax.swing.JLabel();
        Seat = new javax.swing.JLabel();
        Seats = new javax.swing.JPanel();
        SeatTextShow = new javax.swing.JLabel();
        Barcode = new javax.swing.JLabel();
        HorizontalSeperator1 = new javax.swing.JSeparator();
        PrintButton = new javax.swing.JButton();
        CloseButton = new javax.swing.JButton();
        Copyright = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nine Airlines (Confirm)");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(0, 153, 255));
        Header.setToolTipText("");
        Header.setPreferredSize(new java.awt.Dimension(900, 150));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NameMaskapai1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NameMaskapai1.setForeground(new java.awt.Color(255, 255, 255));
        NameMaskapai1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/NameMaskapai.png"))); // NOI18N
        Header.add(NameMaskapai1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        CircleDisable1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CircleDisable.png"))); // NOI18N
        Header.add(CircleDisable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, -1, -1));

        CircleDisable2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CircleDisable.png"))); // NOI18N
        Header.add(CircleDisable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, -1, -1));

        CircleDisable3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CircleDisable.png"))); // NOI18N
        Header.add(CircleDisable3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, -1, -1));

        CircleDisable4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CircleDisable.png"))); // NOI18N
        Header.add(CircleDisable4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 70, -1, -1));

        CircleEnable5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Circle.png"))); // NOI18N
        Header.add(CircleEnable5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 70, -1, -1));

        Line.setForeground(new java.awt.Color(21, 30, 158));
        Line.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Line.png"))); // NOI18N
        Header.add(Line, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 65, 300, 30));

        Progress1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Progress1.setForeground(new java.awt.Color(21, 30, 158));
        Progress1.setText("Destination");
        Header.add(Progress1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, -1, -1));

        Progress2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Progress2.setForeground(new java.awt.Color(21, 30, 158));
        Progress2.setText("Seats");
        Header.add(Progress2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, -1, -1));

        Progress3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Progress3.setForeground(new java.awt.Color(21, 30, 158));
        Progress3.setText("Passenger");
        Header.add(Progress3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, -1, -1));

        Progress4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Progress4.setForeground(new java.awt.Color(21, 30, 158));
        Progress4.setText("Bill");
        Header.add(Progress4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, -1, -1));

        Progress5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Progress5.setForeground(new java.awt.Color(255, 255, 255));
        Progress5.setText("Confirm");
        Header.add(Progress5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 50, -1, -1));

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Bottom.setBackground(new java.awt.Color(255, 255, 255));
        Bottom.setPreferredSize(new java.awt.Dimension(900, 650));
        Bottom.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BookingSummary.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        BookingSummary.setText("Booking Summary");
        Bottom.add(BookingSummary, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 340, 50));

        Please.setBackground(new java.awt.Color(204, 204, 204));
        Please.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Please.setForeground(new java.awt.Color(102, 102, 102));
        Please.setText("Please remember passport No. for flight cancellation.");
        Bottom.add(Please, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 370, -1));

        FirstName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FirstName.setForeground(new java.awt.Color(102, 102, 102));
        FirstName.setText("FIRST NAME");
        Bottom.add(FirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 100, 20));

        FirstNameShow.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        FirstNameShow.setText("------");
        Bottom.add(FirstNameShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 380, 40));

        LastName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        LastName.setForeground(new java.awt.Color(102, 102, 102));
        LastName.setText("LAST NAME");
        Bottom.add(LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 100, 20));

        LastNameShow.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        LastNameShow.setText("------");
        Bottom.add(LastNameShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 400, 40));

        PassportNo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        PassportNo.setForeground(new java.awt.Color(102, 102, 102));
        PassportNo.setText("PASSPORT NO.");
        Bottom.add(PassportNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 130, 20));

        PassportNoShow.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        PassportNoShow.setText("--------");
        Bottom.add(PassportNoShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 390, 40));

        From.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        From.setForeground(new java.awt.Color(102, 102, 102));
        From.setText("FROM");
        Bottom.add(From, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, -1, 12));

        DepartureCode.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        DepartureCode.setForeground(new java.awt.Color(0, 153, 255));
        DepartureCode.setText("---");
        Bottom.add(DepartureCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, -1, 35));

        DepartureName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        DepartureName.setForeground(new java.awt.Color(102, 102, 102));
        DepartureName.setText("-----");
        Bottom.add(DepartureName, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 80, 20));

        PlaneIcon.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        PlaneIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BlackPlane.png"))); // NOI18N
        Bottom.add(PlaneIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 40, -1));

        To.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        To.setForeground(new java.awt.Color(102, 102, 102));
        To.setText("TO");
        Bottom.add(To, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, -1, 12));

        DestinationCode.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        DestinationCode.setForeground(new java.awt.Color(0, 153, 255));
        DestinationCode.setText("---");
        Bottom.add(DestinationCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 150, -1, 35));

        DestinationName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        DestinationName.setForeground(new java.awt.Color(102, 102, 102));
        DestinationName.setText("-----");
        Bottom.add(DestinationName, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 190, 90, 20));

        Date.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Date.setForeground(new java.awt.Color(102, 102, 102));
        Date.setText("DATE");
        Bottom.add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 80, 12));

        DateLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        DateLabel.setForeground(new java.awt.Color(0, 153, 255));
        DateLabel.setText("-- ---");
        Bottom.add(DateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, -1, 30));

        Seat.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Seat.setForeground(new java.awt.Color(102, 102, 102));
        Seat.setText("SEAT");
        Bottom.add(Seat, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, 40, 20));

        Seats.setBackground(new java.awt.Color(0, 153, 255));
        Seats.setForeground(new java.awt.Color(207, 0, 15));

        SeatTextShow.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        SeatTextShow.setForeground(new java.awt.Color(255, 255, 255));
        SeatTextShow.setText("--");

        javax.swing.GroupLayout SeatsLayout = new javax.swing.GroupLayout(Seats);
        Seats.setLayout(SeatsLayout);
        SeatsLayout.setHorizontalGroup(
            SeatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeatsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(SeatTextShow)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        SeatsLayout.setVerticalGroup(
            SeatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeatsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SeatTextShow, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        Bottom.add(Seats, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, 90, 50));

        Barcode.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        Barcode.setForeground(new java.awt.Color(255, 255, 255));
        Barcode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Barcode.png"))); // NOI18N
        Bottom.add(Barcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 270, 70));
        Bottom.add(HorizontalSeperator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 740, 10));

        PrintButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        PrintButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Save.png"))); // NOI18N
        PrintButton.setText("SAVE AS TEXT FILE");
        PrintButton.setFocusPainted(false);
        PrintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintButtonActionPerformed(evt);
            }
        });
        Bottom.add(PrintButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 260, 50));

        CloseButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        CloseButton.setText("CLOSE");
        CloseButton.setFocusPainted(false);
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });
        Bottom.add(CloseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, 260, 50));

        Copyright.setBackground(new java.awt.Color(204, 204, 204));
        Copyright.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Copyright.setForeground(new java.awt.Color(102, 102, 102));
        Copyright.setText("© 2024 Nine Airlines.");
        Bottom.add(Copyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, 210, -1));

        getContentPane().add(Bottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PrintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintButtonActionPerformed
        PrintButton.setText("SAVED");
        PrintButton.setEnabled(false);
        //JOptionPane.showMessageDialog(this, "Boarding pass has been saved.", "", JOptionPane.PLAIN_MESSAGE);
        System.out.println("#### BOARDING PASS SAVED ####");
    }//GEN-LAST:event_PrintButtonActionPerformed

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
        prosesLogin();

    }//GEN-LAST:event_CloseButtonActionPerformed
    
    private void prosesLogin(){
        B_Destination menu = new B_Destination(modelLogin);
        menu.setVisible(true);
        menu.revalidate();
        dispose();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_Confirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_Confirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_Confirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_Confirm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_Confirm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Barcode;
    private javax.swing.JLabel BookingSummary;
    private javax.swing.JPanel Bottom;
    private javax.swing.JLabel CircleDisable1;
    private javax.swing.JLabel CircleDisable2;
    private javax.swing.JLabel CircleDisable3;
    private javax.swing.JLabel CircleDisable4;
    private javax.swing.JLabel CircleEnable5;
    private javax.swing.JButton CloseButton;
    private javax.swing.JLabel Copyright;
    private javax.swing.JLabel Date;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JLabel DepartureCode;
    private javax.swing.JLabel DepartureName;
    private javax.swing.JLabel DestinationCode;
    private javax.swing.JLabel DestinationName;
    private javax.swing.JLabel FirstName;
    private javax.swing.JLabel FirstNameShow;
    private javax.swing.JLabel From;
    private javax.swing.JPanel Header;
    private javax.swing.JSeparator HorizontalSeperator1;
    private javax.swing.JLabel LastName;
    private javax.swing.JLabel LastNameShow;
    private javax.swing.JLabel Line;
    private javax.swing.JLabel NameMaskapai1;
    private javax.swing.JLabel PassportNo;
    private javax.swing.JLabel PassportNoShow;
    private javax.swing.JLabel PlaneIcon;
    private javax.swing.JLabel Please;
    private javax.swing.JButton PrintButton;
    private javax.swing.JLabel Progress1;
    private javax.swing.JLabel Progress2;
    private javax.swing.JLabel Progress3;
    private javax.swing.JLabel Progress4;
    private javax.swing.JLabel Progress5;
    private javax.swing.JLabel Seat;
    private javax.swing.JLabel SeatTextShow;
    private javax.swing.JPanel Seats;
    private javax.swing.JLabel To;
    // End of variables declaration//GEN-END:variables
    
    public void setDate(Date selectedDate) {
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        String dateString = dateFormat.format(selectedDate);
        DateLabel.setText(dateString);
    }
    
    public void setLabelText(String text) {
        DepartureCode.setText(text);
        
    }
    
    public void setLabelText1(String text1) {
        DepartureName.setText(text1);
        
    }
    
    public void setLabelTeks(String teks) {
        DestinationCode.setText(teks);
        
    }
    
    public void setLabelTeks1(String teks1) {
        DestinationName.setText(teks1);
        
    }
    
}