/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Customer;

/**
 *
 * @author harlan
 */
public class Z_About extends javax.swing.JFrame {

    /**
     * Creates new form About
     */
    public Z_About() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        NameMaskapai = new javax.swing.JLabel();
        About = new javax.swing.JLabel();
        NineAirlines = new javax.swing.JLabel();
        Version = new javax.swing.JLabel();
        DevelopedBy = new javax.swing.JLabel();
        OwnerName = new javax.swing.JLabel();
        OwnerNIM = new javax.swing.JLabel();
        OwnerUniversity = new javax.swing.JLabel();
        Text = new javax.swing.JLabel();
        Text2 = new javax.swing.JLabel();
        CloseButton = new javax.swing.JButton();
        Copyright = new javax.swing.JLabel();

        setTitle("About");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(0, 153, 255));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NameMaskapai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameMaskapai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/NameMaskapai.png"))); // NOI18N
        NameMaskapai.setMaximumSize(new java.awt.Dimension(222, 60));
        NameMaskapai.setMinimumSize(new java.awt.Dimension(222, 60));
        NameMaskapai.setMixingCutoutShape(null);
        NameMaskapai.setPreferredSize(new java.awt.Dimension(222, 60));
        Header.add(NameMaskapai, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 200, 80));

        About.setBackground(new java.awt.Color(204, 204, 204));
        About.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        About.setForeground(new java.awt.Color(255, 255, 255));
        About.setText("About");
        Header.add(About, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 120, 40));

        NineAirlines.setBackground(new java.awt.Color(204, 204, 204));
        NineAirlines.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NineAirlines.setForeground(new java.awt.Color(255, 255, 255));
        NineAirlines.setText("Nine Airlines Reservation System");
        Header.add(NineAirlines, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 330, -1));

        Version.setBackground(new java.awt.Color(204, 204, 204));
        Version.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Version.setForeground(new java.awt.Color(255, 255, 255));
        Version.setText("Version : 1.0");
        Header.add(Version, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 140, -1));

        DevelopedBy.setBackground(new java.awt.Color(204, 204, 204));
        DevelopedBy.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        DevelopedBy.setForeground(new java.awt.Color(255, 255, 255));
        DevelopedBy.setText("Developed by");
        Header.add(DevelopedBy, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 140, 40));

        OwnerName.setBackground(new java.awt.Color(204, 204, 204));
        OwnerName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        OwnerName.setForeground(new java.awt.Color(255, 255, 255));
        OwnerName.setText("Group 9");
        Header.add(OwnerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 190, 20));

        OwnerNIM.setBackground(new java.awt.Color(204, 204, 204));
        OwnerNIM.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        OwnerNIM.setForeground(new java.awt.Color(255, 255, 255));
        Header.add(OwnerNIM, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 110, 20));

        OwnerUniversity.setBackground(new java.awt.Color(204, 204, 204));
        OwnerUniversity.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        OwnerUniversity.setForeground(new java.awt.Color(255, 255, 255));
        OwnerUniversity.setText("University Bunda Mulia");
        Header.add(OwnerUniversity, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 210, 20));

        Text.setBackground(new java.awt.Color(204, 204, 204));
        Text.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Text.setForeground(new java.awt.Color(255, 255, 255));
        Text.setText("This application was produced for educational");
        Header.add(Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 350, 20));

        Text2.setBackground(new java.awt.Color(204, 204, 204));
        Text2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Text2.setForeground(new java.awt.Color(255, 255, 255));
        Text2.setText("use and non-profit purpose.");
        Header.add(Text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 310, 20));

        CloseButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        CloseButton.setText("CLOSE");
        CloseButton.setFocusPainted(false);
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });
        Header.add(CloseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 330, 50));

        Copyright.setBackground(new java.awt.Color(204, 204, 204));
        Copyright.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Copyright.setForeground(new java.awt.Color(255, 255, 255));
        Copyright.setText("© 2024 Nine Airlines.");
        Header.add(Copyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 260, -1));

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_CloseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Z_About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Z_About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Z_About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Z_About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Z_About().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel About;
    private javax.swing.JButton CloseButton;
    private javax.swing.JLabel Copyright;
    private javax.swing.JLabel DevelopedBy;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel NameMaskapai;
    private javax.swing.JLabel NineAirlines;
    private javax.swing.JLabel OwnerNIM;
    private javax.swing.JLabel OwnerName;
    private javax.swing.JLabel OwnerUniversity;
    private javax.swing.JLabel Text;
    private javax.swing.JLabel Text2;
    private javax.swing.JLabel Version;
    // End of variables declaration//GEN-END:variables

}