/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import Customer.A_LoginCustomer;

/**
 *
 * @author harlan
 */
public class A_LoginAdmin extends javax.swing.JFrame {

    /**
     * Creates new form LoginAdmin
     */
    public A_LoginAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        NameMaskapai = new javax.swing.JLabel();
        Left = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        Copyright = new javax.swing.JLabel();
        Right = new javax.swing.JPanel();
        Login = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        UsernameField = new javax.swing.JTextField();
        WarningUsername = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        WarningPassword = new javax.swing.JLabel();
        LoginButton = new javax.swing.JButton();
        NotAdmin = new javax.swing.JLabel();
        ClickHere = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nine Airlines (Login)");
        setBackground(new java.awt.Color(255, 255, 255));

        Header.setBackground(new java.awt.Color(0, 153, 255));
        Header.setToolTipText("");
        Header.setPreferredSize(new java.awt.Dimension(900, 150));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NameMaskapai.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NameMaskapai.setForeground(new java.awt.Color(255, 255, 255));
        NameMaskapai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/NameMaskapai.png"))); // NOI18N
        Header.add(NameMaskapai, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        Left.setBackground(new java.awt.Color(0, 153, 255));
        Left.setPreferredSize(new java.awt.Dimension(450, 650));
        Left.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/LogoMaskapai.png"))); // NOI18N
        Left.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 30, -1, -1));

        Copyright.setText("© 2024 Nine Airlines.");
        Copyright.setPreferredSize(new java.awt.Dimension(130, 20));
        Copyright.setRequestFocusEnabled(false);
        Left.add(Copyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, -1, -1));

        Right.setBackground(new java.awt.Color(255, 255, 255));
        Right.setPreferredSize(new java.awt.Dimension(450, 650));
        Right.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        Login.setText("LOGIN ADMIN");
        Login.setPreferredSize(new java.awt.Dimension(260, 45));
        Right.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 100, -1, -1));

        Username.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Username.setForeground(new java.awt.Color(102, 102, 102));
        Username.setText("Username :");
        Right.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 100, 20));

        UsernameField.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Right.add(UsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 300, 35));

        WarningUsername.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        WarningUsername.setForeground(new java.awt.Color(255, 0, 0));
        Right.add(WarningUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 300, 25));

        Password.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Password.setForeground(new java.awt.Color(102, 102, 102));
        Password.setText("Password :");
        Right.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 100, 20));

        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });
        Right.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 300, 35));

        WarningPassword.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        WarningPassword.setForeground(new java.awt.Color(255, 0, 0));
        Right.add(WarningPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 300, 25));

        LoginButton.setText("LOGIN");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        Right.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, -1, -1));

        NotAdmin.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        NotAdmin.setText("Not Admin?");
        Right.add(NotAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, -1, -1));

        ClickHere.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        ClickHere.setText("Click here !");
        ClickHere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClickHereMouseClicked(evt);
            }
        });
        Right.add(ClickHere, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 520, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Left, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(Right, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Left, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Right, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        // TODO add your handling code here:
        B_Dashboard B_Dashboard = new B_Dashboard();
        B_Dashboard.setVisible(true);
        B_Dashboard.revalidate();
            
        dispose();
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void ClickHereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClickHereMouseClicked
        // TODO add your handling code here:
        A_LoginCustomer LoginCustomer = new A_LoginCustomer();
        LoginCustomer.setVisible(true);
        LoginCustomer.revalidate();
            
        dispose();
    }//GEN-LAST:event_ClickHereMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(A_LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(A_LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(A_LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(A_LoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new A_LoginAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ClickHere;
    private javax.swing.JLabel Copyright;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Left;
    private javax.swing.JLabel Login;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel NameMaskapai;
    private javax.swing.JLabel NotAdmin;
    private javax.swing.JLabel Password;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JPanel Right;
    private javax.swing.JLabel Username;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JLabel WarningPassword;
    private javax.swing.JLabel WarningUsername;
    // End of variables declaration//GEN-END:variables
}
