/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

/**
 *
 * @author harlan
 */
public class B_Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public B_Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        NameMaskapai = new javax.swing.JLabel();
        Profile = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Photos = new javax.swing.JLabel();
        Hi = new javax.swing.JLabel();
        NamaLengkap = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        Left = new javax.swing.JPanel();
        Copyright = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        Right = new javax.swing.JPanel();
        Dashboard = new javax.swing.JLabel();
        ManageAccountCust = new javax.swing.JButton();
        ManageDataPassenger = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(0, 153, 255));
        Header.setToolTipText("");
        Header.setPreferredSize(new java.awt.Dimension(900, 150));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NameMaskapai.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NameMaskapai.setForeground(new java.awt.Color(255, 255, 255));
        NameMaskapai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/NameMaskapai.png"))); // NOI18N
        Header.add(NameMaskapai, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, -1, -1));

        Profile.setBackground(new java.awt.Color(0, 153, 255));
        Profile.setPreferredSize(new java.awt.Dimension(320, 163));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Photos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Profile Admin.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(Photos, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(Photos, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Hi.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Hi.setForeground(new java.awt.Color(255, 255, 255));
        Hi.setText("Hi,");

        NamaLengkap.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        NamaLengkap.setForeground(new java.awt.Color(255, 255, 255));
        NamaLengkap.setText("Admin");

        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ProfileLayout = new javax.swing.GroupLayout(Profile);
        Profile.setLayout(ProfileLayout);
        ProfileLayout.setHorizontalGroup(
            ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfileLayout.createSequentialGroup()
                        .addComponent(Hi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NamaLengkap, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ProfileLayout.setVerticalGroup(
            ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfileLayout.createSequentialGroup()
                .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfileLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProfileLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Hi)
                            .addComponent(NamaLengkap))
                        .addGap(50, 50, 50)
                        .addComponent(Logout)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        Header.add(Profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 130));

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Left.setBackground(new java.awt.Color(0, 153, 255));
        Left.setPreferredSize(new java.awt.Dimension(340, 650));
        Left.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Copyright.setText("© 2024 Nine Airlines.");
        Copyright.setPreferredSize(new java.awt.Dimension(130, 20));
        Copyright.setRequestFocusEnabled(false);
        Left.add(Copyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, -1, -1));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/LogoMaskapai.png"))); // NOI18N
        Left.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 50, -1, -1));

        getContentPane().add(Left, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        Right.setBackground(new java.awt.Color(255, 255, 255));
        Right.setPreferredSize(new java.awt.Dimension(560, 650));
        Right.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Dashboard.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        Dashboard.setText("DASHBOARD");
        Right.add(Dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        ManageAccountCust.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ManageAccountCust.setText("Manage Account Customer");
        ManageAccountCust.setFocusPainted(false);
        ManageAccountCust.setPreferredSize(new java.awt.Dimension(185, 25));
        ManageAccountCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageAccountCustActionPerformed(evt);
            }
        });
        Right.add(ManageAccountCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 230, 50));

        ManageDataPassenger.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ManageDataPassenger.setText("Manage Data Passenger");
        ManageDataPassenger.setFocusPainted(false);
        ManageDataPassenger.setPreferredSize(new java.awt.Dimension(185, 25));
        ManageDataPassenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageDataPassengerActionPerformed(evt);
            }
        });
        Right.add(ManageDataPassenger, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 230, 50));

        getContentPane().add(Right, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        A_LoginAdmin A_LoginAdmin = new A_LoginAdmin();
        A_LoginAdmin.setVisible(true);
        A_LoginAdmin.revalidate();

        dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    private void ManageDataPassengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageDataPassengerActionPerformed
        // TODO add your handling code here:
        C_DataPassenger E_ShowData = new C_DataPassenger();
        E_ShowData.setVisible(true);
        E_ShowData.revalidate();

        dispose();
    }//GEN-LAST:event_ManageDataPassengerActionPerformed

    private void ManageAccountCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageAccountCustActionPerformed
        // TODO add your handling code here:
        D_AccountCust F_AccountCust = new D_AccountCust();
        F_AccountCust.setVisible(true);
        F_AccountCust.revalidate();

        dispose();
    }//GEN-LAST:event_ManageAccountCustActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(B_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(B_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(B_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(B_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new B_Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Copyright;
    private javax.swing.JLabel Dashboard;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel Hi;
    private javax.swing.JPanel Left;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton Logout;
    private javax.swing.JButton ManageAccountCust;
    private javax.swing.JButton ManageDataPassenger;
    private javax.swing.JLabel NamaLengkap;
    private javax.swing.JLabel NameMaskapai;
    private javax.swing.JLabel Photos;
    private javax.swing.JPanel Profile;
    private javax.swing.JPanel Right;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
