/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author harlan
 */
public class D_AccountCust extends javax.swing.JFrame {

    /**
     * Creates new form E_ShowData
     */
    DefaultTableModel model;

    public D_AccountCust() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        NameMaskapai = new javax.swing.JLabel();
        Bottom = new javax.swing.JPanel();
        Manage = new javax.swing.JLabel();
        PN = new javax.swing.JLabel();
        PNF = new javax.swing.JTextField();
        U = new javax.swing.JLabel();
        UF = new javax.swing.JTextField();
        PW = new javax.swing.JLabel();
        PWF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Insert = new javax.swing.JButton();
        Search = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Header.setBackground(new java.awt.Color(0, 153, 255));
        Header.setToolTipText("");
        Header.setPreferredSize(new java.awt.Dimension(900, 150));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NameMaskapai.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        NameMaskapai.setForeground(new java.awt.Color(255, 255, 255));
        NameMaskapai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/NameMaskapai.png"))); // NOI18N
        Header.add(NameMaskapai, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        Bottom.setBackground(new java.awt.Color(255, 255, 255));
        Bottom.setPreferredSize(new java.awt.Dimension(900, 650));
        Bottom.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Manage.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        Manage.setText("Manage Account Customer");
        Bottom.add(Manage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 530, 50));

        PN.setText("Passenger Name :");
        Bottom.add(PN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));
        Bottom.add(PNF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 140, -1));

        U.setText("Username :");
        Bottom.add(U, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));
        Bottom.add(UF, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 150, -1));

        PW.setText("Password :");
        Bottom.add(PW, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, -1, -1));
        Bottom.add(PWF, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 150, -1));

        jTable1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Full Name", "Username", "Password"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Bottom.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 860, -1));

        Insert.setText("INSERT");
        Insert.setPreferredSize(new java.awt.Dimension(80, 25));
        Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertActionPerformed(evt);
            }
        });
        Bottom.add(Insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, -1, -1));

        Search.setText("VIEW");
        Search.setPreferredSize(new java.awt.Dimension(81, 25));
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        Bottom.add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 70, -1, -1));

        Update.setText("UPDATE");
        Update.setPreferredSize(new java.awt.Dimension(80, 25));
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        Bottom.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, -1, -1));

        Delete.setText("DELETE");
        Delete.setPreferredSize(new java.awt.Dimension(80, 25));
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        Bottom.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, -1, -1));

        Back.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Back.setText("BACK");
        Back.setFocusPainted(false);
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        Bottom.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 590, 230, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bottom, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Bottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        B_Dashboard B_Dashboard = new B_Dashboard();
        B_Dashboard.setVisible(true);
        B_Dashboard.revalidate();

        dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertActionPerformed
        // TODO add your handling code here:

        try{
            Class.forName("com.mysql.cj.jdbc.Driver");

            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/nineairlines", "root", "");
            String sql = "INSERT INTO customer (F_name, username, password) VALUES (?, ?, ?)";
            PreparedStatement ptst= con.prepareStatement(sql);
            ptst.setString(1,PNF.getText());
            ptst.setString(2,UF.getText());
            ptst.setString(3,PWF.getText());
            ptst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data inserted Succesfully!");
            con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_InsertActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        try {
                String username = UF.getText();
                String fullname = PNF.getText();
                String password = PWF.getText();

                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/nineairlines", "root", "");

                String sql = "UPDATE customer SET F_name = ?, password = ? WHERE username = ?";
                PreparedStatement ptst = con.prepareStatement(sql);
                ptst.setString(1, fullname);
                ptst.setString(2, password);
                ptst.setString(3, username);
                int rowsUpdated = ptst.executeUpdate();

                if (rowsUpdated > 0) {
                    JOptionPane.showMessageDialog(this, "Record Updated!");
                } else {
                    JOptionPane.showMessageDialog(this, "No record found with the given username!");
                }

                con.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
        }

    }//GEN-LAST:event_UpdateActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:

        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/nineairlines", "root", "");
            Statement st = con.createStatement();
            String sql ="SELECT * from customer";
            PreparedStatement ptst= con.prepareStatement(sql);
            ResultSet rs= ptst.executeQuery();
            DefaultTableModel dt= (DefaultTableModel)jTable1.getModel();
            dt.setRowCount(0);
            while(rs.next()){
                Object o[]= {rs.getString("F_name"),rs.getString("username"),rs.getString("password")};
                dt.addRow(o);
            }

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_SearchActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/nineairlines", "root", "");
            Statement st = con.createStatement();

            String username= UF.getText();
            String sql = "DELETE FROM `customer` WHERE username='"+username+"'";
            PreparedStatement ptst = con.prepareStatement(sql);
            ptst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data deleted succsessfully");
            con.close();

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_DeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(D_AccountCust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(D_AccountCust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(D_AccountCust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(D_AccountCust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new D_AccountCust().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JPanel Bottom;
    private javax.swing.JButton Delete;
    private javax.swing.JPanel Header;
    private javax.swing.JButton Insert;
    private javax.swing.JLabel Manage;
    private javax.swing.JLabel NameMaskapai;
    private javax.swing.JLabel PN;
    private javax.swing.JTextField PNF;
    private javax.swing.JLabel PW;
    private javax.swing.JTextField PWF;
    private javax.swing.JButton Search;
    private javax.swing.JLabel U;
    private javax.swing.JTextField UF;
    private javax.swing.JButton Update;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
